import type { SellerProblemContract } from "./SellerProblemUX";

export const sellerProblemUXFixtures = {
  confirmedLossProblem: {
    id: "fixture-confirmed-loss",
    title: "Товар продаётся ниже безопасной маржи",
    why: "Цена, комиссия и себестоимость дают отрицательную прибыль по подтверждённым данным.",
    impactText: "Подтверждённый убыток: 18 400 ₽",
    impactAmount: 18400,
    trustState: "confirmed",
    impactType: "confirmed_loss",
    severity: "critical",
    status: "new",
    nextStep: "Проверить цену и не снижать её без безопасной маржи.",
    canFixHere: true,
    canFixHereText: "Да, откройте проверку цены из карточки проблемы.",
    recheckRule: "После изменения цены платформа сравнит маржу и продажи.",
    result: null,
    showResultBlock: false,
    evidenceLedger: null,
    evidenceQuality: "full",
    allowedActions: ["open_price_review", "recheck", "dismiss"],
  },
  estimatedOverstockProblem: {
    id: "fixture-estimated-overstock",
    title: "Остаток замораживает деньги",
    why: "Продажи ниже темпа, а остатка хватит на слишком долгий период.",
    impactText: "Замороженные деньги: 92 000 ₽",
    impactAmount: 92000,
    trustState: "estimated",
    impactType: "blocked_cash",
    severity: "high",
    status: "in_progress",
    nextStep: "Проверить промо или план распродажи без ухода ниже маржи.",
    canFixHere: true,
    canFixHereText: "Да, можно открыть промо или задачу на распродажу.",
    recheckRule: "После действия проверяем оборачиваемость и остаток.",
    result: { status: "pending_data", detail: "Ждём данные после действия.", amount: null },
    showResultBlock: true,
    evidenceLedger: null,
    evidenceQuality: "full",
    allowedActions: ["open_promo_planner", "recheck", "dismiss"],
  },
  blockedMissingCostProblem: {
    id: "fixture-blocked-missing-cost",
    title: "Не хватает себестоимости",
    why: "Без себестоимости платформа не может подтвердить прибыль и маржу.",
    impactText: "Блокер данных",
    impactAmount: null,
    trustState: "blocked",
    impactType: "data_blocker",
    severity: "high",
    status: "new",
    nextStep: "Загрузить или заполнить себестоимость.",
    canFixHere: true,
    canFixHereText: "Да, откройте исправление данных.",
    recheckRule: "После загрузки себестоимости запускаем повторную проверку.",
    result: null,
    showResultBlock: false,
    evidenceLedger: null,
    evidenceQuality: "full",
    allowedActions: ["open_data_fix", "upload_cost", "recheck"],
  },
  opportunityCheckerContentProblem: {
    id: "fixture-checker-opportunity",
    title: "Карточку можно улучшить",
    why: "Проверка карточки нашла слабое описание и предлагает более понятный текст.",
    impactText: "Возможность роста",
    impactAmount: null,
    trustState: "opportunity",
    impactType: "opportunity",
    severity: "medium",
    status: "new",
    nextStep: "Проверить предложенное исправление и сохранить решение.",
    canFixHere: true,
    canFixHereText: "Да, исправление доступно в проверке карточки.",
    recheckRule: "После сохранения решения карточка проверяется повторно.",
    result: null,
    showResultBlock: false,
    evidenceLedger: null,
    evidenceQuality: "partial",
    allowedActions: ["check_card_quality", "recheck", "dismiss"],
  },
  testOnlyAdminProblem: {
    id: "fixture-test-only",
    title: "Тестовое правило для администратора",
    why: "Правило проверяется перед показом продавцам.",
    impactText: "Тестовое правило",
    impactAmount: null,
    trustState: "test_only",
    impactType: "system_warning",
    severity: "low",
    status: "test_only",
    nextStep: "Проверить правило в админском режиме.",
    canFixHere: false,
    canFixHereText: "Нет, это админская проверка.",
    recheckRule: "Повторная проверка доступна после публикации правила.",
    result: { status: "not_enough_data", detail: "Нет данных для продавца.", amount: null },
    showResultBlock: true,
    evidenceLedger: null,
    evidenceQuality: "partial",
    allowedActions: ["recheck"],
  },
} satisfies Record<string, SellerProblemContract>;
