"""Initial schema.

Revision ID: 20260514_000001
Revises:
Create Date: 2026-05-14 12:50:00
"""
from __future__ import annotations

from alembic import op

revision = "20260514_000001"
down_revision = None
branch_labels = None
depends_on = None

DDL_STATEMENTS = [
    """CREATE TABLE auth_users (
	email VARCHAR(255) NOT NULL, 
	full_name VARCHAR(255) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	is_superuser BOOLEAN NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_auth_users PRIMARY KEY (id)
)""",
    """CREATE TABLE wb_accounts (
	name VARCHAR(255) NOT NULL, 
	seller_name VARCHAR(255), 
	external_account_id VARCHAR(255), 
	timezone VARCHAR(64) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_accounts PRIMARY KEY (id)
)""",
    """CREATE TABLE auth_refresh_tokens (
	user_id BIGINT NOT NULL, 
	token_fingerprint VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_auth_refresh_tokens PRIMARY KEY (id), 
	CONSTRAINT uq_auth_refresh_tokens_token_fingerprint UNIQUE (token_fingerprint), 
	CONSTRAINT fk_auth_refresh_tokens_user_id_auth_users FOREIGN KEY(user_id) REFERENCES auth_users (id) ON DELETE CASCADE
)""",
    """CREATE TABLE core_sku (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	supplier_article VARCHAR(255), 
	barcode VARCHAR(255), 
	sku VARCHAR(255), 
	chrt_id INTEGER, 
	size_id INTEGER, 
	tech_size VARCHAR(64), 
	title VARCHAR(500), 
	brand VARCHAR(255), 
	subject_id INTEGER, 
	subject_name VARCHAR(255), 
	source_updated_at TIMESTAMP WITH TIME ZONE, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_core_sku PRIMARY KEY (id), 
	CONSTRAINT uq_core_sku_account_id UNIQUE (account_id, nm_id, vendor_code, tech_size, chrt_id, size_id, barcode), 
	CONSTRAINT fk_core_sku_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE data_quality_issues (
	account_id BIGINT, 
	domain VARCHAR(64) NOT NULL, 
	severity VARCHAR(32) NOT NULL, 
	code VARCHAR(128) NOT NULL, 
	entity_key VARCHAR(255), 
	message TEXT NOT NULL, 
	payload JSONB NOT NULL, 
	detected_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	resolved_at TIMESTAMP WITH TIME ZONE, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_data_quality_issues PRIMARY KEY (id), 
	CONSTRAINT fk_data_quality_issues_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE SET NULL
)""",
    """CREATE TABLE manual_cost_uploads (
	account_id BIGINT NOT NULL, 
	created_by_user_id BIGINT, 
	filename VARCHAR(255) NOT NULL, 
	content_type VARCHAR(100), 
	rows_total INTEGER NOT NULL, 
	rows_valid INTEGER NOT NULL, 
	rows_invalid INTEGER NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	error_text TEXT, 
	imported_at TIMESTAMP WITH TIME ZONE, 
	summary JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_manual_cost_uploads PRIMARY KEY (id), 
	CONSTRAINT fk_manual_cost_uploads_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_manual_cost_uploads_created_by_user_id_auth_users FOREIGN KEY(created_by_user_id) REFERENCES auth_users (id) ON DELETE SET NULL
)""",
    """CREATE TABLE raw_wb_api_responses (
	account_id BIGINT NOT NULL, 
	api_category VARCHAR(64) NOT NULL, 
	endpoint VARCHAR(255) NOT NULL, 
	http_method VARCHAR(16) NOT NULL, 
	request_params JSONB NOT NULL, 
	request_body JSONB, 
	response_json JSONB NOT NULL, 
	response_text TEXT, 
	status_code INTEGER NOT NULL, 
	is_success BOOLEAN NOT NULL, 
	retry_count INTEGER NOT NULL, 
	requested_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	loaded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	hash VARCHAR(64) NOT NULL, 
	request_fingerprint VARCHAR(64), 
	response_fingerprint VARCHAR(64), 
	error_text TEXT, 
	id BIGSERIAL NOT NULL, 
	CONSTRAINT pk_raw_wb_api_responses PRIMARY KEY (id), 
	CONSTRAINT fk_raw_wb_api_responses_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_acquiring_reports (
	account_id BIGINT NOT NULL, 
	report_id BIGINT, 
	date_from DATE, 
	date_to DATE, 
	create_date DATE, 
	currency VARCHAR(8), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_acquiring_reports PRIMARY KEY (id), 
	CONSTRAINT uq_wb_acquiring_reports_account_id UNIQUE (account_id, report_id), 
	CONSTRAINT fk_wb_acquiring_reports_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_ad_campaigns (
	account_id BIGINT NOT NULL, 
	advert_id INTEGER NOT NULL, 
	campaign_type INTEGER, 
	status INTEGER, 
	bid_type VARCHAR(64), 
	name VARCHAR(255), 
	change_time TIMESTAMP WITH TIME ZONE, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_ad_campaigns PRIMARY KEY (id), 
	CONSTRAINT uq_wb_ad_campaigns_account_id UNIQUE (account_id, advert_id), 
	CONSTRAINT fk_wb_ad_campaigns_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_ad_cluster_stats (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	advert_id INTEGER NOT NULL, 
	stat_date DATE NOT NULL, 
	cluster VARCHAR(255), 
	nm_id INTEGER, 
	views INTEGER, 
	clicks INTEGER, 
	ctr NUMERIC(18, 4), 
	cpc NUMERIC(18, 4), 
	cpm NUMERIC(18, 4), 
	orders INTEGER, 
	atbs INTEGER, 
	sum NUMERIC(18, 4), 
	avg_position NUMERIC(18, 4), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_ad_cluster_stats PRIMARY KEY (id), 
	CONSTRAINT fk_wb_ad_cluster_stats_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_ad_stats_daily (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	advert_id INTEGER NOT NULL, 
	stat_date DATE NOT NULL, 
	nm_id INTEGER, 
	views INTEGER, 
	clicks INTEGER, 
	ctr NUMERIC(18, 4), 
	cpc NUMERIC(18, 4), 
	cpm NUMERIC(18, 4), 
	atbs INTEGER, 
	orders INTEGER, 
	shks INTEGER, 
	sum NUMERIC(18, 4), 
	sum_price NUMERIC(18, 4), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_ad_stats_daily PRIMARY KEY (id), 
	CONSTRAINT uq_wb_ad_stats_daily_account_id UNIQUE (account_id, advert_id, stat_date, nm_id), 
	CONSTRAINT fk_wb_ad_stats_daily_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_api_tokens (
	account_id BIGINT NOT NULL, 
	category VARCHAR(64) NOT NULL, 
	token_encrypted TEXT NOT NULL, 
	comment VARCHAR(255), 
	is_active BOOLEAN NOT NULL, 
	last_used_at VARCHAR(64), 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_api_tokens PRIMARY KEY (id), 
	CONSTRAINT uq_wb_api_tokens_account_id UNIQUE (account_id, category), 
	CONSTRAINT fk_wb_api_tokens_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_balance_snapshots (
	account_id BIGINT NOT NULL, 
	snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	currency VARCHAR(8), 
	current NUMERIC(18, 4), 
	for_withdraw NUMERIC(18, 4), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_balance_snapshots PRIMARY KEY (id), 
	CONSTRAINT fk_wb_balance_snapshots_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_card_funnel_daily (
	account_id BIGINT NOT NULL, 
	stat_date DATE NOT NULL, 
	nm_id INTEGER NOT NULL, 
	vendor_code VARCHAR(255), 
	title VARCHAR(500), 
	brand_name VARCHAR(255), 
	subject_id INTEGER, 
	subject_name VARCHAR(255), 
	open_count INTEGER, 
	cart_count INTEGER, 
	order_count INTEGER, 
	buyout_count INTEGER, 
	cancel_count INTEGER, 
	add_to_cart_conversion NUMERIC(18, 4), 
	cart_to_order_conversion NUMERIC(18, 4), 
	buyout_percent NUMERIC(18, 4), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_card_funnel_daily PRIMARY KEY (id), 
	CONSTRAINT uq_wb_card_funnel_daily_account_id UNIQUE (account_id, stat_date, nm_id), 
	CONSTRAINT fk_wb_card_funnel_daily_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_document_categories (
	account_id BIGINT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	title VARCHAR(255), 
	locale VARCHAR(8) NOT NULL, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_document_categories PRIMARY KEY (id), 
	CONSTRAINT uq_wb_document_categories_account_id UNIQUE (account_id, name), 
	CONSTRAINT fk_wb_document_categories_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_documents (
	account_id BIGINT NOT NULL, 
	document_key VARCHAR(255) NOT NULL, 
	title VARCHAR(255), 
	category VARCHAR(255), 
	document_date DATE, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_documents PRIMARY KEY (id), 
	CONSTRAINT uq_wb_documents_account_id UNIQUE (account_id, document_key), 
	CONSTRAINT fk_wb_documents_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_hidden_products (
	account_id BIGINT NOT NULL, 
	hidden_type VARCHAR(32) NOT NULL, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	title VARCHAR(500), 
	reason VARCHAR(1000), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_hidden_products PRIMARY KEY (id), 
	CONSTRAINT fk_wb_hidden_products_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_orders (
	account_id BIGINT NOT NULL, 
	date TIMESTAMP WITH TIME ZONE, 
	last_change_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	srid VARCHAR(255) NOT NULL, 
	g_number VARCHAR(255), 
	order_id BIGINT, 
	nm_id INTEGER, 
	supplier_article VARCHAR(255), 
	barcode VARCHAR(255), 
	warehouse_name VARCHAR(255), 
	warehouse_type VARCHAR(255), 
	region_name VARCHAR(255), 
	oblast_okrug_name VARCHAR(255), 
	country_name VARCHAR(255), 
	total_price NUMERIC(18, 4), 
	discount_percent INTEGER, 
	spp NUMERIC(18, 4), 
	finished_price NUMERIC(18, 4), 
	price_with_disc NUMERIC(18, 4), 
	is_cancel BOOLEAN, 
	cancel_date TIMESTAMP WITH TIME ZONE, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_orders PRIMARY KEY (id), 
	CONSTRAINT uq_wb_orders_account_id UNIQUE (account_id, srid, last_change_date), 
	CONSTRAINT fk_wb_orders_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_price_quarantine (
	account_id BIGINT NOT NULL, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_price_quarantine PRIMARY KEY (id), 
	CONSTRAINT fk_wb_price_quarantine_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_price_sizes (
	account_id BIGINT NOT NULL, 
	nm_id INTEGER NOT NULL, 
	size_id INTEGER NOT NULL, 
	vendor_code VARCHAR(255), 
	tech_size_name VARCHAR(64), 
	price NUMERIC(18, 4), 
	discounted_price NUMERIC(18, 4), 
	club_discounted_price NUMERIC(18, 4), 
	discount INTEGER, 
	club_discount INTEGER, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_price_sizes PRIMARY KEY (id), 
	CONSTRAINT uq_wb_price_sizes_account_id UNIQUE (account_id, nm_id, size_id), 
	CONSTRAINT fk_wb_price_sizes_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_price_snapshots (
	account_id BIGINT NOT NULL, 
	nm_id INTEGER NOT NULL, 
	vendor_code VARCHAR(255), 
	snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_price_snapshots PRIMARY KEY (id), 
	CONSTRAINT fk_wb_price_snapshots_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_price_upload_tasks (
	account_id BIGINT NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	task_key VARCHAR(128) NOT NULL, 
	status VARCHAR(64), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_price_upload_tasks PRIMARY KEY (id), 
	CONSTRAINT uq_wb_price_upload_tasks_account_id UNIQUE (account_id, source, task_key), 
	CONSTRAINT fk_wb_price_upload_tasks_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_prices (
	account_id BIGINT NOT NULL, 
	nm_id INTEGER NOT NULL, 
	vendor_code VARCHAR(255), 
	currency_iso_code VARCHAR(8), 
	discount INTEGER, 
	club_discount INTEGER, 
	editable_size_price BOOLEAN, 
	is_bad_turnover BOOLEAN, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_prices PRIMARY KEY (id), 
	CONSTRAINT uq_wb_prices_account_id UNIQUE (account_id, nm_id), 
	CONSTRAINT fk_wb_prices_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_product_cards (
	account_id BIGINT NOT NULL, 
	nm_id INTEGER NOT NULL, 
	imt_id INTEGER, 
	nm_uuid VARCHAR(128), 
	subject_id INTEGER, 
	subject_name VARCHAR(255), 
	vendor_code VARCHAR(255), 
	title VARCHAR(500), 
	description TEXT, 
	brand VARCHAR(255), 
	need_kiz BOOLEAN, 
	kiz_marked BOOLEAN, 
	photos JSONB, 
	video VARCHAR(1000), 
	dimensions JSONB, 
	created_at_wb TIMESTAMP WITH TIME ZONE, 
	updated_at_wb TIMESTAMP WITH TIME ZONE, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_product_cards PRIMARY KEY (id), 
	CONSTRAINT uq_wb_product_cards_account_id UNIQUE (account_id, nm_id), 
	CONSTRAINT fk_wb_product_cards_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_realization_reports (
	account_id BIGINT NOT NULL, 
	report_id BIGINT, 
	report_name VARCHAR(255), 
	period VARCHAR(32), 
	date_from DATE, 
	date_to DATE, 
	create_date DATE, 
	currency VARCHAR(8), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_realization_reports PRIMARY KEY (id), 
	CONSTRAINT uq_wb_realization_reports_account_id UNIQUE (account_id, report_id), 
	CONSTRAINT fk_wb_realization_reports_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_region_sales_daily (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	stat_date DATE NOT NULL, 
	region_name VARCHAR(255), 
	country_name VARCHAR(255), 
	city_name VARCHAR(255), 
	federal_district VARCHAR(255), 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	sale_amount NUMERIC(18, 4), 
	sale_amount_percent NUMERIC(18, 4), 
	sale_quantity INTEGER, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_region_sales_daily PRIMARY KEY (id), 
	CONSTRAINT uq_wb_region_sales_daily_account_id UNIQUE (account_id, stat_date, country_name, region_name, city_name, nm_id, vendor_code), 
	CONSTRAINT fk_wb_region_sales_daily_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_sales (
	account_id BIGINT NOT NULL, 
	date TIMESTAMP WITH TIME ZONE, 
	last_change_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	srid VARCHAR(255) NOT NULL, 
	sale_id VARCHAR(255), 
	order_id BIGINT, 
	nm_id INTEGER, 
	supplier_article VARCHAR(255), 
	barcode VARCHAR(255), 
	warehouse_name VARCHAR(255), 
	total_price NUMERIC(18, 4), 
	discount_percent INTEGER, 
	price_with_disc NUMERIC(18, 4), 
	finished_price NUMERIC(18, 4), 
	for_pay NUMERIC(18, 4), 
	spp NUMERIC(18, 4), 
	is_supply BOOLEAN, 
	is_realization BOOLEAN, 
	is_cancel BOOLEAN, 
	sticker VARCHAR(255), 
	category VARCHAR(255), 
	subject VARCHAR(255), 
	brand VARCHAR(255), 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_sales PRIMARY KEY (id), 
	CONSTRAINT uq_wb_sales_account_id UNIQUE (account_id, srid, last_change_date), 
	CONSTRAINT fk_wb_sales_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_stock_snapshots (
	account_id BIGINT NOT NULL, 
	snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	task_id VARCHAR(128), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_stock_snapshots PRIMARY KEY (id), 
	CONSTRAINT fk_wb_stock_snapshots_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_supplies (
	account_id BIGINT NOT NULL, 
	supply_id INTEGER NOT NULL, 
	preorder_id INTEGER, 
	create_date TIMESTAMP WITH TIME ZONE, 
	supply_date TIMESTAMP WITH TIME ZONE, 
	fact_date TIMESTAMP WITH TIME ZONE, 
	updated_date TIMESTAMP WITH TIME ZONE, 
	status_id INTEGER, 
	warehouse_id INTEGER, 
	warehouse_name VARCHAR(255), 
	actual_warehouse_id INTEGER, 
	actual_warehouse_name VARCHAR(255), 
	box_type_id INTEGER, 
	last_enriched_at TIMESTAMP WITH TIME ZONE, 
	goods_synced_at TIMESTAMP WITH TIME ZONE, 
	packages_synced_at TIMESTAMP WITH TIME ZONE, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_supplies PRIMARY KEY (id), 
	CONSTRAINT uq_wb_supplies_account_id UNIQUE (account_id, supply_id), 
	CONSTRAINT fk_wb_supplies_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_supply_acceptance_options (
	account_id BIGINT NOT NULL, 
	warehouse_id INTEGER, 
	warehouse_name VARCHAR(255), 
	box_type_id INTEGER, 
	coefficient VARCHAR(64), 
	allow_unload BOOLEAN, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_supply_acceptance_options PRIMARY KEY (id), 
	CONSTRAINT fk_wb_supply_acceptance_options_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_supply_warehouses (
	account_id BIGINT NOT NULL, 
	warehouse_id INTEGER NOT NULL, 
	name VARCHAR(255), 
	address VARCHAR(500), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_supply_warehouses PRIMARY KEY (id), 
	CONSTRAINT uq_wb_supply_warehouses_account_id UNIQUE (account_id, warehouse_id), 
	CONSTRAINT fk_wb_supply_warehouses_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_sync_cursors (
	account_id BIGINT NOT NULL, 
	domain VARCHAR(64) NOT NULL, 
	cursor_key VARCHAR(128) NOT NULL, 
	cursor_value JSONB NOT NULL, 
	last_synced_at TIMESTAMP WITH TIME ZONE, 
	status VARCHAR(32) NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_sync_cursors PRIMARY KEY (id), 
	CONSTRAINT uq_wb_sync_cursors_account_id UNIQUE (account_id, domain, cursor_key), 
	CONSTRAINT fk_wb_sync_cursors_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_sync_runs (
	account_id BIGINT NOT NULL, 
	domain VARCHAR(64) NOT NULL, 
	trigger VARCHAR(32) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	is_backfill BOOLEAN NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	details JSONB NOT NULL, 
	error_text TEXT, 
	id BIGSERIAL NOT NULL, 
	CONSTRAINT pk_wb_sync_runs PRIMARY KEY (id), 
	CONSTRAINT fk_wb_sync_runs_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_tariff_acceptance (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	collected_at DATE NOT NULL, 
	warehouse_id INTEGER, 
	warehouse_name VARCHAR(255), 
	coefficient VARCHAR(64), 
	allow_unload BOOLEAN, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_tariff_acceptance PRIMARY KEY (id), 
	CONSTRAINT fk_wb_tariff_acceptance_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_tariff_boxes (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	collected_at DATE NOT NULL, 
	warehouse_name VARCHAR(255), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_tariff_boxes PRIMARY KEY (id), 
	CONSTRAINT fk_wb_tariff_boxes_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_tariff_commissions (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	collected_at DATE NOT NULL, 
	parent_id INTEGER, 
	parent_name VARCHAR(255), 
	subject_id INTEGER, 
	subject_name VARCHAR(255), 
	kgvp_marketplace NUMERIC(18, 4), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_tariff_commissions PRIMARY KEY (id), 
	CONSTRAINT fk_wb_tariff_commissions_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_tariff_pallets (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	collected_at DATE NOT NULL, 
	warehouse_name VARCHAR(255), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_tariff_pallets PRIMARY KEY (id), 
	CONSTRAINT fk_wb_tariff_pallets_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_tariff_returns (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	collected_at DATE NOT NULL, 
	warehouse_name VARCHAR(255), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_tariff_returns PRIMARY KEY (id), 
	CONSTRAINT fk_wb_tariff_returns_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE manual_costs (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	upload_id BIGINT, 
	uploaded_by_user_id BIGINT, 
	sku_id BIGINT, 
	vendor_code VARCHAR(255) NOT NULL, 
	nm_id INTEGER, 
	barcode VARCHAR(255), 
	tech_size VARCHAR(50), 
	unit_cost NUMERIC(18, 4) NOT NULL, 
	cost_price NUMERIC(18, 4) NOT NULL, 
	packaging_cost NUMERIC(18, 4) NOT NULL, 
	inbound_logistics_cost NUMERIC(18, 4) NOT NULL, 
	supplier VARCHAR(255), 
	currency VARCHAR(8) NOT NULL, 
	valid_from DATE, 
	valid_to DATE, 
	source_file_name VARCHAR(255), 
	uploaded_at TIMESTAMP WITH TIME ZONE, 
	match_rule VARCHAR(64), 
	is_ambiguous BOOLEAN NOT NULL, 
	comment TEXT, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_manual_costs PRIMARY KEY (id), 
	CONSTRAINT uq_manual_costs_account_id UNIQUE (account_id, vendor_code, nm_id, barcode, tech_size, valid_from), 
	CONSTRAINT fk_manual_costs_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_manual_costs_upload_id_manual_cost_uploads FOREIGN KEY(upload_id) REFERENCES manual_cost_uploads (id) ON DELETE SET NULL, 
	CONSTRAINT fk_manual_costs_uploaded_by_user_id_auth_users FOREIGN KEY(uploaded_by_user_id) REFERENCES auth_users (id) ON DELETE SET NULL, 
	CONSTRAINT fk_manual_costs_sku_id_core_sku FOREIGN KEY(sku_id) REFERENCES core_sku (id) ON DELETE SET NULL
)""",
    """CREATE TABLE mart_finance_reconciliation (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	stat_date DATE NOT NULL, 
	srid VARCHAR(255) NOT NULL, 
	sku_id BIGINT, 
	order_id BIGINT, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	barcode VARCHAR(255), 
	order_date DATE, 
	sale_date DATE, 
	finance_sale_date DATE, 
	finance_rr_date DATE, 
	first_seen_at TIMESTAMP WITH TIME ZONE, 
	last_seen_at TIMESTAMP WITH TIME ZONE, 
	order_rows INTEGER NOT NULL, 
	sale_rows INTEGER NOT NULL, 
	finance_rows INTEGER NOT NULL, 
	has_order BOOLEAN NOT NULL, 
	has_sale BOOLEAN NOT NULL, 
	has_finance BOOLEAN NOT NULL, 
	order_revenue NUMERIC(18, 4), 
	sale_revenue NUMERIC(18, 4), 
	finance_revenue NUMERIC(18, 4), 
	sale_for_pay NUMERIC(18, 4), 
	finance_for_pay NUMERIC(18, 4), 
	revenue_delta NUMERIC(18, 4), 
	for_pay_delta NUMERIC(18, 4), 
	status VARCHAR(64) NOT NULL, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_mart_finance_reconciliation PRIMARY KEY (id), 
	CONSTRAINT uq_mart_finance_reconciliation_account_id UNIQUE (account_id, stat_date, srid, nm_id), 
	CONSTRAINT fk_mart_finance_reconciliation_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_mart_finance_reconciliation_sku_id_core_sku FOREIGN KEY(sku_id) REFERENCES core_sku (id) ON DELETE SET NULL
)""",
    """CREATE TABLE mart_sku_daily (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	stat_date DATE NOT NULL, 
	sku_id BIGINT, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	barcode VARCHAR(255), 
	title VARCHAR(500), 
	brand VARCHAR(255), 
	subject_name VARCHAR(255), 
	order_rows INTEGER NOT NULL, 
	ordered_units INTEGER NOT NULL, 
	cancelled_orders INTEGER NOT NULL, 
	sale_rows INTEGER NOT NULL, 
	finance_rows INTEGER NOT NULL, 
	operational_sales_qty INTEGER NOT NULL, 
	operational_return_qty INTEGER NOT NULL, 
	operational_revenue NUMERIC(18, 4), 
	operational_for_pay NUMERIC(18, 4), 
	finance_sales_qty INTEGER NOT NULL, 
	finance_return_qty INTEGER NOT NULL, 
	finance_net_units INTEGER NOT NULL, 
	finance_revenue NUMERIC(18, 4), 
	finance_for_pay NUMERIC(18, 4), 
	final_sales_qty INTEGER NOT NULL, 
	final_return_qty INTEGER NOT NULL, 
	final_net_qty INTEGER NOT NULL, 
	final_revenue NUMERIC(18, 4), 
	final_for_pay NUMERIC(18, 4), 
	final_revenue_source VARCHAR(32), 
	commission NUMERIC(18, 4), 
	acquiring_fee NUMERIC(18, 4), 
	logistics NUMERIC(18, 4), 
	paid_acceptance NUMERIC(18, 4), 
	storage NUMERIC(18, 4), 
	penalties NUMERIC(18, 4), 
	deductions NUMERIC(18, 4), 
	additional_payments NUMERIC(18, 4), 
	ad_spend NUMERIC(18, 4), 
	ad_views INTEGER NOT NULL, 
	ad_clicks INTEGER NOT NULL, 
	funnel_opens INTEGER NOT NULL, 
	funnel_carts INTEGER NOT NULL, 
	funnel_orders INTEGER NOT NULL, 
	funnel_buyouts INTEGER NOT NULL, 
	current_price NUMERIC(18, 4), 
	current_discounted_price NUMERIC(18, 4), 
	seller_discount INTEGER, 
	club_discount INTEGER, 
	cost_price NUMERIC(18, 4), 
	packaging_cost NUMERIC(18, 4), 
	inbound_logistics_cost NUMERIC(18, 4), 
	total_unit_cost NUMERIC(18, 4), 
	estimated_cogs NUMERIC(18, 4), 
	estimated_profit_before_ads NUMERIC(18, 4), 
	estimated_profit_after_ads NUMERIC(18, 4), 
	has_manual_cost BOOLEAN NOT NULL, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_mart_sku_daily PRIMARY KEY (id), 
	CONSTRAINT uq_mart_sku_daily_account_id UNIQUE (account_id, stat_date, nm_id, vendor_code, barcode), 
	CONSTRAINT fk_mart_sku_daily_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_mart_sku_daily_sku_id_core_sku FOREIGN KEY(sku_id) REFERENCES core_sku (id) ON DELETE SET NULL
)""",
    """CREATE TABLE mart_stock_daily (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	stat_date DATE NOT NULL, 
	sku_id BIGINT, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	barcode VARCHAR(255), 
	warehouse_id INTEGER, 
	warehouse_name VARCHAR(255), 
	quantity NUMERIC(18, 4), 
	quantity_full NUMERIC(18, 4), 
	in_way_to_client NUMERIC(18, 4), 
	in_way_from_client NUMERIC(18, 4), 
	days_since_last_sale INTEGER, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_mart_stock_daily PRIMARY KEY (id), 
	CONSTRAINT uq_mart_stock_daily_account_id UNIQUE (account_id, stat_date, nm_id, barcode, warehouse_id, warehouse_name), 
	CONSTRAINT fk_mart_stock_daily_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_mart_stock_daily_sku_id_core_sku FOREIGN KEY(sku_id) REFERENCES core_sku (id) ON DELETE SET NULL
)""",
    """CREATE TABLE wb_acquiring_report_rows (
	account_id BIGINT NOT NULL, 
	dedupe_key VARCHAR(64) NOT NULL, 
	report_id_fk BIGINT, 
	report_id BIGINT, 
	order_id BIGINT, 
	srid VARCHAR(255), 
	shk_id BIGINT, 
	nm_id INTEGER, 
	retail_amount NUMERIC(18, 4), 
	acquiring_fee NUMERIC(18, 4), 
	currency VARCHAR(8), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_acquiring_report_rows PRIMARY KEY (id), 
	CONSTRAINT uq_wb_acquiring_report_rows_account_id UNIQUE (account_id, report_id, order_id, srid, shk_id, nm_id), 
	CONSTRAINT fk_wb_acquiring_report_rows_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_acquiring_report_rows_report_id_fk_wb_acquiring_reports FOREIGN KEY(report_id_fk) REFERENCES wb_acquiring_reports (id) ON DELETE SET NULL
)""",
    """CREATE TABLE wb_ad_campaign_items (
	campaign_fk_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	nm_id INTEGER, 
	name VARCHAR(255), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_ad_campaign_items PRIMARY KEY (id), 
	CONSTRAINT fk_wb_ad_campaign_items_campaign_fk_id_wb_ad_campaigns FOREIGN KEY(campaign_fk_id) REFERENCES wb_ad_campaigns (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_ad_campaign_items_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_price_upload_task_rows (
	upload_task_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	error_text VARCHAR(1000), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_price_upload_task_rows PRIMARY KEY (id), 
	CONSTRAINT fk_wb_price_upload_task_rows_upload_task_id_wb_price_up_27f6 FOREIGN KEY(upload_task_id) REFERENCES wb_price_upload_tasks (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_price_upload_task_rows_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_product_card_characteristics (
	product_card_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	char_id INTEGER, 
	name VARCHAR(255), 
	value JSONB, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_product_card_characteristics PRIMARY KEY (id), 
	CONSTRAINT fk_wb_product_card_characteristics_product_card_id_wb_p_2b4e FOREIGN KEY(product_card_id) REFERENCES wb_product_cards (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_product_card_characteristics_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_product_card_sizes (
	product_card_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	chrt_id INTEGER, 
	size_id INTEGER, 
	tech_size VARCHAR(64), 
	skus JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_product_card_sizes PRIMARY KEY (id), 
	CONSTRAINT fk_wb_product_card_sizes_product_card_id_wb_product_cards FOREIGN KEY(product_card_id) REFERENCES wb_product_cards (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_product_card_sizes_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_product_card_tags (
	product_card_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	tag_id INTEGER NOT NULL, 
	name VARCHAR(255), 
	color VARCHAR(32), 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_product_card_tags PRIMARY KEY (id), 
	CONSTRAINT fk_wb_product_card_tags_product_card_id_wb_product_cards FOREIGN KEY(product_card_id) REFERENCES wb_product_cards (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_product_card_tags_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_realization_report_rows (
	account_id BIGINT NOT NULL, 
	report_id_fk BIGINT, 
	rrd_id BIGINT NOT NULL, 
	rr_date DATE, 
	sale_dt TIMESTAMP WITH TIME ZONE, 
	order_id BIGINT, 
	srid VARCHAR(255), 
	shk_id BIGINT, 
	nm_id INTEGER, 
	report_id BIGINT, 
	doc_type_name VARCHAR(255), 
	operation_type VARCHAR(64), 
	is_sale_operation BOOLEAN, 
	is_return_operation BOOLEAN, 
	is_expense_operation BOOLEAN, 
	is_reconcilable BOOLEAN, 
	quantity INTEGER, 
	vendor_code VARCHAR(255), 
	barcode VARCHAR(255), 
	title VARCHAR(500), 
	brand VARCHAR(255), 
	subject_name VARCHAR(255), 
	office_name VARCHAR(255), 
	seller_oper_name VARCHAR(255), 
	bonus_type_name VARCHAR(255), 
	retail_amount NUMERIC(18, 4), 
	retail_price NUMERIC(18, 4), 
	retail_price_with_disc NUMERIC(18, 4), 
	delivery_amount NUMERIC(18, 4), 
	delivery_service NUMERIC(18, 4), 
	paid_acceptance NUMERIC(18, 4), 
	additional_payment NUMERIC(18, 4), 
	rebill_logistic_cost NUMERIC(18, 4), 
	return_amount NUMERIC(18, 4), 
	ppvz_sales_commission NUMERIC(18, 4), 
	acquiring_fee NUMERIC(18, 4), 
	paid_storage NUMERIC(18, 4), 
	penalty NUMERIC(18, 4), 
	deduction NUMERIC(18, 4), 
	for_pay NUMERIC(18, 4), 
	currency VARCHAR(8), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_realization_report_rows PRIMARY KEY (id), 
	CONSTRAINT uq_wb_realization_report_rows_account_id UNIQUE (account_id, rrd_id), 
	CONSTRAINT fk_wb_realization_report_rows_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_realization_report_rows_report_id_fk_wb_realizati_5e27 FOREIGN KEY(report_id_fk) REFERENCES wb_realization_reports (id) ON DELETE SET NULL
)""",
    """CREATE TABLE wb_stock_snapshot_rows (
	snapshot_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	nm_id INTEGER, 
	barcode VARCHAR(255), 
	chrt_id INTEGER, 
	size_id INTEGER, 
	warehouse_id INTEGER, 
	warehouse_name VARCHAR(255), 
	quantity NUMERIC(18, 4), 
	quantity_full NUMERIC(18, 4), 
	in_way_to_client NUMERIC(18, 4), 
	in_way_from_client NUMERIC(18, 4), 
	subject VARCHAR(255), 
	brand VARCHAR(255), 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_stock_snapshot_rows PRIMARY KEY (id), 
	CONSTRAINT fk_wb_stock_snapshot_rows_snapshot_id_wb_stock_snapshots FOREIGN KEY(snapshot_id) REFERENCES wb_stock_snapshots (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_stock_snapshot_rows_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_supply_goods (
	supply_fk_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	nm_id INTEGER, 
	vendor_code VARCHAR(255), 
	barcode VARCHAR(255), 
	tech_size VARCHAR(64), 
	quantity INTEGER, 
	accepted_quantity INTEGER, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_supply_goods PRIMARY KEY (id), 
	CONSTRAINT fk_wb_supply_goods_supply_fk_id_wb_supplies FOREIGN KEY(supply_fk_id) REFERENCES wb_supplies (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_supply_goods_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE TABLE wb_supply_packages (
	supply_fk_id BIGINT NOT NULL, 
	account_id BIGINT NOT NULL, 
	package_code VARCHAR(255), 
	quantity INTEGER, 
	barcodes JSONB NOT NULL, 
	payload JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_wb_supply_packages PRIMARY KEY (id), 
	CONSTRAINT fk_wb_supply_packages_supply_fk_id_wb_supplies FOREIGN KEY(supply_fk_id) REFERENCES wb_supplies (id) ON DELETE CASCADE, 
	CONSTRAINT fk_wb_supply_packages_account_id_wb_accounts FOREIGN KEY(account_id) REFERENCES wb_accounts (id) ON DELETE CASCADE
)""",
    """CREATE OR REPLACE VIEW v_wb_orders_current AS
SELECT *
FROM (
    SELECT
        wb_orders.*,
        row_number() OVER (
            PARTITION BY wb_orders.account_id, wb_orders.srid
            ORDER BY wb_orders.last_change_date DESC, wb_orders.id DESC
        ) AS rn
    FROM wb_orders
) ranked
WHERE ranked.rn = 1""",
    """CREATE OR REPLACE VIEW v_wb_sales_current AS
SELECT *
FROM (
    SELECT
        wb_sales.*,
        row_number() OVER (
            PARTITION BY wb_sales.account_id, wb_sales.srid
            ORDER BY wb_sales.last_change_date DESC, wb_sales.id DESC
        ) AS rn
    FROM wb_sales
) ranked
WHERE ranked.rn = 1""",
    """CREATE OR REPLACE VIEW v_core_sku_enriched AS
SELECT
    sku.id,
    sku.account_id,
    sku.nm_id,
    sku.vendor_code,
    sku.barcode,
    sku.tech_size,
    sku.title,
    sku.brand,
    sku.subject_id,
    sku.subject_name,
    price_meta.currency_iso_code,
    price_meta.discount,
    price_meta.club_discount,
    price_values.current_price,
    price_values.current_discounted_price,
    cost.id AS manual_cost_id,
    cost.cost_price,
    cost.packaging_cost,
    cost.inbound_logistics_cost,
    (COALESCE(cost.cost_price, cost.unit_cost, 0) + COALESCE(cost.packaging_cost, 0) + COALESCE(cost.inbound_logistics_cost, 0)) AS total_unit_cost,
    stock.snapshot_at AS latest_stock_snapshot_at,
    stock.quantity AS latest_quantity,
    stock.quantity_full AS latest_quantity_full,
    stock.in_way_to_client AS latest_in_way_to_client,
    stock.in_way_from_client AS latest_in_way_from_client
FROM core_sku sku
LEFT JOIN LATERAL (
    SELECT p.*
    FROM wb_prices p
    WHERE p.account_id = sku.account_id AND p.nm_id = sku.nm_id
    ORDER BY p.id DESC
    LIMIT 1
) price_meta ON TRUE
LEFT JOIN LATERAL (
    SELECT
        MIN(ps.price) AS current_price,
        MIN(ps.discounted_price) AS current_discounted_price
    FROM wb_price_sizes ps
    WHERE ps.account_id = sku.account_id AND ps.nm_id = sku.nm_id
) price_values ON TRUE
LEFT JOIN LATERAL (
    SELECT mc.*
    FROM manual_costs mc
    WHERE mc.account_id = sku.account_id
      AND mc.sku_id = sku.id
      AND (mc.valid_from IS NULL OR mc.valid_from <= CURRENT_DATE)
      AND (mc.valid_to IS NULL OR mc.valid_to >= CURRENT_DATE)
    ORDER BY mc.valid_from DESC NULLS LAST, mc.id DESC
    LIMIT 1
) cost ON TRUE
LEFT JOIN LATERAL (
    SELECT snap.snapshot_at, row.quantity, row.quantity_full, row.in_way_to_client, row.in_way_from_client
    FROM wb_stock_snapshot_rows row
    JOIN wb_stock_snapshots snap ON snap.id = row.snapshot_id
    WHERE row.account_id = sku.account_id
      AND row.nm_id = sku.nm_id
      AND (row.barcode IS NOT DISTINCT FROM sku.barcode)
    ORDER BY snap.snapshot_at DESC, row.id DESC
    LIMIT 1
) stock ON TRUE""",
]

INDEX_STATEMENTS = [
    """CREATE UNIQUE INDEX ix_auth_users_email ON auth_users (email)""",
    """CREATE UNIQUE INDEX ix_wb_accounts_name ON wb_accounts (name)""",
    """CREATE INDEX ix_auth_refresh_tokens_token_fingerprint ON auth_refresh_tokens (token_fingerprint)""",
    """CREATE INDEX ix_core_sku_barcode ON core_sku (barcode)""",
    """CREATE INDEX ix_core_sku_nm_id ON core_sku (nm_id)""",
    """CREATE UNIQUE INDEX ix_core_sku_dedupe_key ON core_sku (dedupe_key)""",
    """CREATE INDEX ix_core_sku_vendor_code ON core_sku (vendor_code)""",
    """CREATE INDEX ix_data_quality_issues_domain ON data_quality_issues (domain)""",
    """CREATE INDEX ix_data_quality_issues_code ON data_quality_issues (code)""",
    """CREATE INDEX ix_raw_wb_api_responses_api_category ON raw_wb_api_responses (api_category)""",
    """CREATE INDEX ix_raw_wb_api_responses_endpoint ON raw_wb_api_responses (endpoint)""",
    """CREATE INDEX ix_raw_wb_api_responses_response_fingerprint ON raw_wb_api_responses (response_fingerprint)""",
    """CREATE INDEX ix_raw_wb_api_responses_hash ON raw_wb_api_responses (hash)""",
    """CREATE INDEX ix_raw_wb_api_responses_account_endpoint ON raw_wb_api_responses (account_id, endpoint)""",
    """CREATE INDEX ix_raw_wb_api_responses_request_fingerprint ON raw_wb_api_responses (request_fingerprint)""",
    """CREATE INDEX ix_wb_acquiring_reports_report_id ON wb_acquiring_reports (report_id)""",
    """CREATE INDEX ix_wb_ad_campaigns_advert_id ON wb_ad_campaigns (advert_id)""",
    """CREATE UNIQUE INDEX ix_wb_ad_cluster_stats_dedupe_key ON wb_ad_cluster_stats (dedupe_key)""",
    """CREATE INDEX ix_wb_ad_cluster_stats_stat_date ON wb_ad_cluster_stats (stat_date)""",
    """CREATE INDEX ix_wb_ad_cluster_stats_advert_id ON wb_ad_cluster_stats (advert_id)""",
    """CREATE INDEX ix_wb_ad_cluster_stats_nm_id ON wb_ad_cluster_stats (nm_id)""",
    """CREATE INDEX ix_wb_ad_stats_daily_stat_date ON wb_ad_stats_daily (stat_date)""",
    """CREATE UNIQUE INDEX ix_wb_ad_stats_daily_dedupe_key ON wb_ad_stats_daily (dedupe_key)""",
    """CREATE INDEX ix_wb_ad_stats_daily_advert_id ON wb_ad_stats_daily (advert_id)""",
    """CREATE INDEX ix_wb_ad_stats_daily_nm_id ON wb_ad_stats_daily (nm_id)""",
    """CREATE INDEX ix_wb_api_tokens_category ON wb_api_tokens (category)""",
    """CREATE INDEX ix_wb_balance_snapshots_snapshot_at ON wb_balance_snapshots (snapshot_at)""",
    """CREATE INDEX ix_wb_card_funnel_daily_stat_date ON wb_card_funnel_daily (stat_date)""",
    """CREATE INDEX ix_wb_card_funnel_daily_nm_id ON wb_card_funnel_daily (nm_id)""",
    """CREATE INDEX ix_wb_document_categories_name ON wb_document_categories (name)""",
    """CREATE INDEX ix_wb_documents_document_key ON wb_documents (document_key)""",
    """CREATE INDEX ix_wb_hidden_products_nm_id ON wb_hidden_products (nm_id)""",
    """CREATE INDEX ix_wb_hidden_products_hidden_type ON wb_hidden_products (hidden_type)""",
    """CREATE INDEX ix_wb_orders_nm_id ON wb_orders (nm_id)""",
    """CREATE INDEX ix_wb_orders_srid ON wb_orders (srid)""",
    """CREATE INDEX ix_wb_orders_last_change_date ON wb_orders (last_change_date)""",
    """CREATE INDEX ix_wb_price_quarantine_nm_id ON wb_price_quarantine (nm_id)""",
    """CREATE INDEX ix_wb_price_sizes_size_id ON wb_price_sizes (size_id)""",
    """CREATE INDEX ix_wb_price_sizes_nm_id ON wb_price_sizes (nm_id)""",
    """CREATE INDEX ix_wb_price_snapshots_nm_id ON wb_price_snapshots (nm_id)""",
    """CREATE INDEX ix_wb_prices_nm_id ON wb_prices (nm_id)""",
    """CREATE INDEX ix_wb_product_cards_nm_id ON wb_product_cards (nm_id)""",
    """CREATE INDEX ix_wb_product_cards_vendor_code ON wb_product_cards (vendor_code)""",
    """CREATE INDEX ix_wb_realization_reports_report_id ON wb_realization_reports (report_id)""",
    """CREATE UNIQUE INDEX ix_wb_region_sales_daily_dedupe_key ON wb_region_sales_daily (dedupe_key)""",
    """CREATE INDEX ix_wb_region_sales_daily_nm_id ON wb_region_sales_daily (nm_id)""",
    """CREATE INDEX ix_wb_region_sales_daily_stat_date ON wb_region_sales_daily (stat_date)""",
    """CREATE INDEX ix_wb_sales_nm_id ON wb_sales (nm_id)""",
    """CREATE INDEX ix_wb_sales_srid ON wb_sales (srid)""",
    """CREATE INDEX ix_wb_sales_last_change_date ON wb_sales (last_change_date)""",
    """CREATE INDEX ix_wb_stock_snapshots_snapshot_at ON wb_stock_snapshots (snapshot_at)""",
    """CREATE INDEX ix_wb_supplies_supply_id ON wb_supplies (supply_id)""",
    """CREATE INDEX ix_wb_supply_acceptance_options_warehouse_id ON wb_supply_acceptance_options (warehouse_id)""",
    """CREATE INDEX ix_wb_supply_warehouses_warehouse_id ON wb_supply_warehouses (warehouse_id)""",
    """CREATE INDEX ix_wb_sync_cursors_domain ON wb_sync_cursors (domain)""",
    """CREATE INDEX ix_wb_sync_runs_domain ON wb_sync_runs (domain)""",
    """CREATE UNIQUE INDEX ix_wb_tariff_acceptance_dedupe_key ON wb_tariff_acceptance (dedupe_key)""",
    """CREATE INDEX ix_wb_tariff_acceptance_collected_at ON wb_tariff_acceptance (collected_at)""",
    """CREATE UNIQUE INDEX ix_wb_tariff_boxes_dedupe_key ON wb_tariff_boxes (dedupe_key)""",
    """CREATE INDEX ix_wb_tariff_boxes_collected_at ON wb_tariff_boxes (collected_at)""",
    """CREATE UNIQUE INDEX ix_wb_tariff_commissions_dedupe_key ON wb_tariff_commissions (dedupe_key)""",
    """CREATE INDEX ix_wb_tariff_commissions_collected_at ON wb_tariff_commissions (collected_at)""",
    """CREATE UNIQUE INDEX ix_wb_tariff_pallets_dedupe_key ON wb_tariff_pallets (dedupe_key)""",
    """CREATE INDEX ix_wb_tariff_pallets_collected_at ON wb_tariff_pallets (collected_at)""",
    """CREATE INDEX ix_wb_tariff_returns_collected_at ON wb_tariff_returns (collected_at)""",
    """CREATE UNIQUE INDEX ix_wb_tariff_returns_dedupe_key ON wb_tariff_returns (dedupe_key)""",
    """CREATE INDEX ix_manual_costs_nm_id ON manual_costs (nm_id)""",
    """CREATE INDEX ix_manual_costs_barcode ON manual_costs (barcode)""",
    """CREATE UNIQUE INDEX ix_manual_costs_dedupe_key ON manual_costs (dedupe_key)""",
    """CREATE INDEX ix_manual_costs_vendor_code ON manual_costs (vendor_code)""",
    """CREATE INDEX ix_manual_costs_sku_id ON manual_costs (sku_id)""",
    """CREATE UNIQUE INDEX ix_mart_finance_reconciliation_dedupe_key ON mart_finance_reconciliation (dedupe_key)""",
    """CREATE INDEX ix_mart_finance_reconciliation_srid ON mart_finance_reconciliation (srid)""",
    """CREATE INDEX ix_mart_finance_reconciliation_sku_id ON mart_finance_reconciliation (sku_id)""",
    """CREATE INDEX ix_mart_finance_reconciliation_nm_id ON mart_finance_reconciliation (nm_id)""",
    """CREATE INDEX ix_mart_finance_reconciliation_stat_date ON mart_finance_reconciliation (stat_date)""",
    """CREATE INDEX ix_mart_sku_daily_nm_id ON mart_sku_daily (nm_id)""",
    """CREATE INDEX ix_mart_sku_daily_stat_date ON mart_sku_daily (stat_date)""",
    """CREATE INDEX ix_mart_sku_daily_sku_id ON mart_sku_daily (sku_id)""",
    """CREATE UNIQUE INDEX ix_mart_sku_daily_dedupe_key ON mart_sku_daily (dedupe_key)""",
    """CREATE INDEX ix_mart_stock_daily_nm_id ON mart_stock_daily (nm_id)""",
    """CREATE INDEX ix_mart_stock_daily_stat_date ON mart_stock_daily (stat_date)""",
    """CREATE INDEX ix_mart_stock_daily_sku_id ON mart_stock_daily (sku_id)""",
    """CREATE UNIQUE INDEX ix_mart_stock_daily_dedupe_key ON mart_stock_daily (dedupe_key)""",
    """CREATE UNIQUE INDEX ix_wb_acquiring_report_rows_dedupe_key ON wb_acquiring_report_rows (dedupe_key)""",
    """CREATE INDEX ix_wb_acquiring_report_rows_srid ON wb_acquiring_report_rows (srid)""",
    """CREATE INDEX ix_wb_acquiring_report_rows_nm_id ON wb_acquiring_report_rows (nm_id)""",
    """CREATE INDEX ix_wb_acquiring_report_rows_report_id ON wb_acquiring_report_rows (report_id)""",
    """CREATE INDEX ix_wb_ad_campaign_items_nm_id ON wb_ad_campaign_items (nm_id)""",
    """CREATE INDEX ix_wb_price_upload_task_rows_nm_id ON wb_price_upload_task_rows (nm_id)""",
    """CREATE INDEX ix_wb_product_card_tags_tag_id ON wb_product_card_tags (tag_id)""",
    """CREATE INDEX ix_wb_realization_report_rows_srid ON wb_realization_report_rows (srid)""",
    """CREATE INDEX ix_wb_realization_report_rows_rrd_id ON wb_realization_report_rows (rrd_id)""",
    """CREATE INDEX ix_wb_realization_report_rows_report_id ON wb_realization_report_rows (report_id)""",
    """CREATE INDEX ix_wb_realization_report_rows_nm_id ON wb_realization_report_rows (nm_id)""",
    """CREATE INDEX ix_wb_stock_snapshot_rows_nm_id ON wb_stock_snapshot_rows (nm_id)""",
    """CREATE INDEX ix_wb_supply_goods_nm_id ON wb_supply_goods (nm_id)""",
]

def upgrade() -> None:
    for statement in DDL_STATEMENTS:
        op.execute(statement)
    for statement in INDEX_STATEMENTS:
        op.execute(statement)

def downgrade() -> None:
    raise NotImplementedError("Downgrade is not supported for the initial forward-only schema.")
