/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStockControlRouteImport } from './routes/_authenticated/stock-control'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedReputationRouteImport } from './routes/_authenticated/reputation'
import { Route as AuthenticatedPurchasePlanRouteImport } from './routes/_authenticated/purchase-plan'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPhotoStudioRouteImport } from './routes/_authenticated/photo-studio'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedMartsRouteImport } from './routes/_authenticated/marts'
import { Route as AuthenticatedGroupingRouteImport } from './routes/_authenticated/grouping'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedDataFixRouteImport } from './routes/_authenticated/data-fix'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedActionCenterRouteImport } from './routes/_authenticated/action-center'
import { Route as AuthenticatedAbTestsRouteImport } from './routes/_authenticated/ab-tests'
import { Route as AuthenticatedSkuIndexRouteImport } from './routes/_authenticated/sku.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedCheckerIndexRouteImport } from './routes/_authenticated/checker.index'
import { Route as AuthenticatedCardsIndexRouteImport } from './routes/_authenticated/cards.index'
import { Route as AuthenticatedSkuIdRouteImport } from './routes/_authenticated/sku.$id'
import { Route as AuthenticatedProductsNmIdRouteImport } from './routes/_authenticated/products.$nmId'
import { Route as AuthenticatedCheckerFixedFileRouteImport } from './routes/_authenticated/checker.fixed-file'
import { Route as AuthenticatedCheckerNmIdRouteImport } from './routes/_authenticated/checker.$nmId'
import { Route as AuthenticatedCardsNmIdRouteImport } from './routes/_authenticated/cards.$nmId'
import { Route as AuthenticatedAdminProblemRulesRouteImport } from './routes/_authenticated/admin.problem-rules'
import { Route as AuthenticatedAbTestsCompanyIdRouteImport } from './routes/_authenticated/ab-tests.$companyId'
import { Route as AuthenticatedPhotoStudioProjectsProjectIdRouteImport } from './routes/_authenticated/photo-studio.projects.$projectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockControlRoute =
  AuthenticatedStockControlRouteImport.update({
    id: '/stock-control',
    path: '/stock-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReputationRoute = AuthenticatedReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasePlanRoute =
  AuthenticatedPurchasePlanRouteImport.update({
    id: '/purchase-plan',
    path: '/purchase-plan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhotoStudioRoute =
  AuthenticatedPhotoStudioRouteImport.update({
    id: '/photo-studio',
    path: '/photo-studio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMartsRoute = AuthenticatedMartsRouteImport.update({
  id: '/marts',
  path: '/marts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupingRoute = AuthenticatedGroupingRouteImport.update({
  id: '/grouping',
  path: '/grouping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataFixRoute = AuthenticatedDataFixRouteImport.update({
  id: '/data-fix',
  path: '/data-fix',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionCenterRoute =
  AuthenticatedActionCenterRouteImport.update({
    id: '/action-center',
    path: '/action-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAbTestsRoute = AuthenticatedAbTestsRouteImport.update({
  id: '/ab-tests',
  path: '/ab-tests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSkuIndexRoute = AuthenticatedSkuIndexRouteImport.update({
  id: '/sku/',
  path: '/sku/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckerIndexRoute =
  AuthenticatedCheckerIndexRouteImport.update({
    id: '/checker/',
    path: '/checker/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCardsIndexRoute = AuthenticatedCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSkuIdRoute = AuthenticatedSkuIdRouteImport.update({
  id: '/sku/$id',
  path: '/sku/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsNmIdRoute =
  AuthenticatedProductsNmIdRouteImport.update({
    id: '/products/$nmId',
    path: '/products/$nmId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckerFixedFileRoute =
  AuthenticatedCheckerFixedFileRouteImport.update({
    id: '/checker/fixed-file',
    path: '/checker/fixed-file',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckerNmIdRoute =
  AuthenticatedCheckerNmIdRouteImport.update({
    id: '/checker/$nmId',
    path: '/checker/$nmId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCardsNmIdRoute = AuthenticatedCardsNmIdRouteImport.update({
  id: '/cards/$nmId',
  path: '/cards/$nmId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminProblemRulesRoute =
  AuthenticatedAdminProblemRulesRouteImport.update({
    id: '/problem-rules',
    path: '/problem-rules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAbTestsCompanyIdRoute =
  AuthenticatedAbTestsCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedAbTestsRoute,
  } as any)
const AuthenticatedPhotoStudioProjectsProjectIdRoute =
  AuthenticatedPhotoStudioProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedPhotoStudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ab-tests': typeof AuthenticatedAbTestsRouteWithChildren
  '/action-center': typeof AuthenticatedActionCenterRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ads': typeof AuthenticatedAdsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-fix': typeof AuthenticatedDataFixRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/grouping': typeof AuthenticatedGroupingRoute
  '/marts': typeof AuthenticatedMartsRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/photo-studio': typeof AuthenticatedPhotoStudioRouteWithChildren
  '/pricing': typeof AuthenticatedPricingRoute
  '/purchase-plan': typeof AuthenticatedPurchasePlanRoute
  '/reputation': typeof AuthenticatedReputationRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stock-control': typeof AuthenticatedStockControlRoute
  '/ab-tests/$companyId': typeof AuthenticatedAbTestsCompanyIdRoute
  '/admin/problem-rules': typeof AuthenticatedAdminProblemRulesRoute
  '/cards/$nmId': typeof AuthenticatedCardsNmIdRoute
  '/checker/$nmId': typeof AuthenticatedCheckerNmIdRoute
  '/checker/fixed-file': typeof AuthenticatedCheckerFixedFileRoute
  '/products/$nmId': typeof AuthenticatedProductsNmIdRoute
  '/sku/$id': typeof AuthenticatedSkuIdRoute
  '/cards/': typeof AuthenticatedCardsIndexRoute
  '/checker/': typeof AuthenticatedCheckerIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/sku/': typeof AuthenticatedSkuIndexRoute
  '/photo-studio/projects/$projectId': typeof AuthenticatedPhotoStudioProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ab-tests': typeof AuthenticatedAbTestsRouteWithChildren
  '/action-center': typeof AuthenticatedActionCenterRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ads': typeof AuthenticatedAdsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-fix': typeof AuthenticatedDataFixRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/grouping': typeof AuthenticatedGroupingRoute
  '/marts': typeof AuthenticatedMartsRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/photo-studio': typeof AuthenticatedPhotoStudioRouteWithChildren
  '/pricing': typeof AuthenticatedPricingRoute
  '/purchase-plan': typeof AuthenticatedPurchasePlanRoute
  '/reputation': typeof AuthenticatedReputationRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stock-control': typeof AuthenticatedStockControlRoute
  '/ab-tests/$companyId': typeof AuthenticatedAbTestsCompanyIdRoute
  '/admin/problem-rules': typeof AuthenticatedAdminProblemRulesRoute
  '/cards/$nmId': typeof AuthenticatedCardsNmIdRoute
  '/checker/$nmId': typeof AuthenticatedCheckerNmIdRoute
  '/checker/fixed-file': typeof AuthenticatedCheckerFixedFileRoute
  '/products/$nmId': typeof AuthenticatedProductsNmIdRoute
  '/sku/$id': typeof AuthenticatedSkuIdRoute
  '/cards': typeof AuthenticatedCardsIndexRoute
  '/checker': typeof AuthenticatedCheckerIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/sku': typeof AuthenticatedSkuIndexRoute
  '/photo-studio/projects/$projectId': typeof AuthenticatedPhotoStudioProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ab-tests': typeof AuthenticatedAbTestsRouteWithChildren
  '/_authenticated/action-center': typeof AuthenticatedActionCenterRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-fix': typeof AuthenticatedDataFixRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/grouping': typeof AuthenticatedGroupingRoute
  '/_authenticated/marts': typeof AuthenticatedMartsRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/photo-studio': typeof AuthenticatedPhotoStudioRouteWithChildren
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/purchase-plan': typeof AuthenticatedPurchasePlanRoute
  '/_authenticated/reputation': typeof AuthenticatedReputationRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/stock-control': typeof AuthenticatedStockControlRoute
  '/_authenticated/ab-tests/$companyId': typeof AuthenticatedAbTestsCompanyIdRoute
  '/_authenticated/admin/problem-rules': typeof AuthenticatedAdminProblemRulesRoute
  '/_authenticated/cards/$nmId': typeof AuthenticatedCardsNmIdRoute
  '/_authenticated/checker/$nmId': typeof AuthenticatedCheckerNmIdRoute
  '/_authenticated/checker/fixed-file': typeof AuthenticatedCheckerFixedFileRoute
  '/_authenticated/products/$nmId': typeof AuthenticatedProductsNmIdRoute
  '/_authenticated/sku/$id': typeof AuthenticatedSkuIdRoute
  '/_authenticated/cards/': typeof AuthenticatedCardsIndexRoute
  '/_authenticated/checker/': typeof AuthenticatedCheckerIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/sku/': typeof AuthenticatedSkuIndexRoute
  '/_authenticated/photo-studio/projects/$projectId': typeof AuthenticatedPhotoStudioProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ab-tests'
    | '/action-center'
    | '/actions'
    | '/admin'
    | '/ads'
    | '/analytics'
    | '/catalog'
    | '/claims'
    | '/costs'
    | '/dashboard'
    | '/data-fix'
    | '/doctor'
    | '/expenses'
    | '/finance'
    | '/grouping'
    | '/marts'
    | '/money'
    | '/operations'
    | '/photo-studio'
    | '/pricing'
    | '/purchase-plan'
    | '/reputation'
    | '/results'
    | '/settings'
    | '/stock'
    | '/stock-control'
    | '/ab-tests/$companyId'
    | '/admin/problem-rules'
    | '/cards/$nmId'
    | '/checker/$nmId'
    | '/checker/fixed-file'
    | '/products/$nmId'
    | '/sku/$id'
    | '/cards/'
    | '/checker/'
    | '/products/'
    | '/sku/'
    | '/photo-studio/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ab-tests'
    | '/action-center'
    | '/actions'
    | '/admin'
    | '/ads'
    | '/analytics'
    | '/catalog'
    | '/claims'
    | '/costs'
    | '/dashboard'
    | '/data-fix'
    | '/doctor'
    | '/expenses'
    | '/finance'
    | '/grouping'
    | '/marts'
    | '/money'
    | '/operations'
    | '/photo-studio'
    | '/pricing'
    | '/purchase-plan'
    | '/reputation'
    | '/results'
    | '/settings'
    | '/stock'
    | '/stock-control'
    | '/ab-tests/$companyId'
    | '/admin/problem-rules'
    | '/cards/$nmId'
    | '/checker/$nmId'
    | '/checker/fixed-file'
    | '/products/$nmId'
    | '/sku/$id'
    | '/cards'
    | '/checker'
    | '/products'
    | '/sku'
    | '/photo-studio/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ab-tests'
    | '/_authenticated/action-center'
    | '/_authenticated/actions'
    | '/_authenticated/admin'
    | '/_authenticated/ads'
    | '/_authenticated/analytics'
    | '/_authenticated/catalog'
    | '/_authenticated/claims'
    | '/_authenticated/costs'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-fix'
    | '/_authenticated/doctor'
    | '/_authenticated/expenses'
    | '/_authenticated/finance'
    | '/_authenticated/grouping'
    | '/_authenticated/marts'
    | '/_authenticated/money'
    | '/_authenticated/operations'
    | '/_authenticated/photo-studio'
    | '/_authenticated/pricing'
    | '/_authenticated/purchase-plan'
    | '/_authenticated/reputation'
    | '/_authenticated/results'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/stock-control'
    | '/_authenticated/ab-tests/$companyId'
    | '/_authenticated/admin/problem-rules'
    | '/_authenticated/cards/$nmId'
    | '/_authenticated/checker/$nmId'
    | '/_authenticated/checker/fixed-file'
    | '/_authenticated/products/$nmId'
    | '/_authenticated/sku/$id'
    | '/_authenticated/cards/'
    | '/_authenticated/checker/'
    | '/_authenticated/products/'
    | '/_authenticated/sku/'
    | '/_authenticated/photo-studio/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock-control': {
      id: '/_authenticated/stock-control'
      path: '/stock-control'
      fullPath: '/stock-control'
      preLoaderRoute: typeof AuthenticatedStockControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reputation': {
      id: '/_authenticated/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof AuthenticatedReputationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-plan': {
      id: '/_authenticated/purchase-plan'
      path: '/purchase-plan'
      fullPath: '/purchase-plan'
      preLoaderRoute: typeof AuthenticatedPurchasePlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/photo-studio': {
      id: '/_authenticated/photo-studio'
      path: '/photo-studio'
      fullPath: '/photo-studio'
      preLoaderRoute: typeof AuthenticatedPhotoStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marts': {
      id: '/_authenticated/marts'
      path: '/marts'
      fullPath: '/marts'
      preLoaderRoute: typeof AuthenticatedMartsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grouping': {
      id: '/_authenticated/grouping'
      path: '/grouping'
      fullPath: '/grouping'
      preLoaderRoute: typeof AuthenticatedGroupingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-fix': {
      id: '/_authenticated/data-fix'
      path: '/data-fix'
      fullPath: '/data-fix'
      preLoaderRoute: typeof AuthenticatedDataFixRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/action-center': {
      id: '/_authenticated/action-center'
      path: '/action-center'
      fullPath: '/action-center'
      preLoaderRoute: typeof AuthenticatedActionCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ab-tests': {
      id: '/_authenticated/ab-tests'
      path: '/ab-tests'
      fullPath: '/ab-tests'
      preLoaderRoute: typeof AuthenticatedAbTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sku/': {
      id: '/_authenticated/sku/'
      path: '/sku'
      fullPath: '/sku/'
      preLoaderRoute: typeof AuthenticatedSkuIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checker/': {
      id: '/_authenticated/checker/'
      path: '/checker'
      fullPath: '/checker/'
      preLoaderRoute: typeof AuthenticatedCheckerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cards/': {
      id: '/_authenticated/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof AuthenticatedCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sku/$id': {
      id: '/_authenticated/sku/$id'
      path: '/sku/$id'
      fullPath: '/sku/$id'
      preLoaderRoute: typeof AuthenticatedSkuIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$nmId': {
      id: '/_authenticated/products/$nmId'
      path: '/products/$nmId'
      fullPath: '/products/$nmId'
      preLoaderRoute: typeof AuthenticatedProductsNmIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checker/fixed-file': {
      id: '/_authenticated/checker/fixed-file'
      path: '/checker/fixed-file'
      fullPath: '/checker/fixed-file'
      preLoaderRoute: typeof AuthenticatedCheckerFixedFileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checker/$nmId': {
      id: '/_authenticated/checker/$nmId'
      path: '/checker/$nmId'
      fullPath: '/checker/$nmId'
      preLoaderRoute: typeof AuthenticatedCheckerNmIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cards/$nmId': {
      id: '/_authenticated/cards/$nmId'
      path: '/cards/$nmId'
      fullPath: '/cards/$nmId'
      preLoaderRoute: typeof AuthenticatedCardsNmIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/problem-rules': {
      id: '/_authenticated/admin/problem-rules'
      path: '/problem-rules'
      fullPath: '/admin/problem-rules'
      preLoaderRoute: typeof AuthenticatedAdminProblemRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/ab-tests/$companyId': {
      id: '/_authenticated/ab-tests/$companyId'
      path: '/$companyId'
      fullPath: '/ab-tests/$companyId'
      preLoaderRoute: typeof AuthenticatedAbTestsCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAbTestsRoute
    }
    '/_authenticated/photo-studio/projects/$projectId': {
      id: '/_authenticated/photo-studio/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/photo-studio/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedPhotoStudioProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedPhotoStudioRoute
    }
  }
}

interface AuthenticatedAbTestsRouteChildren {
  AuthenticatedAbTestsCompanyIdRoute: typeof AuthenticatedAbTestsCompanyIdRoute
}

const AuthenticatedAbTestsRouteChildren: AuthenticatedAbTestsRouteChildren = {
  AuthenticatedAbTestsCompanyIdRoute: AuthenticatedAbTestsCompanyIdRoute,
}

const AuthenticatedAbTestsRouteWithChildren =
  AuthenticatedAbTestsRoute._addFileChildren(AuthenticatedAbTestsRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminProblemRulesRoute: typeof AuthenticatedAdminProblemRulesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminProblemRulesRoute: AuthenticatedAdminProblemRulesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPhotoStudioRouteChildren {
  AuthenticatedPhotoStudioProjectsProjectIdRoute: typeof AuthenticatedPhotoStudioProjectsProjectIdRoute
}

const AuthenticatedPhotoStudioRouteChildren: AuthenticatedPhotoStudioRouteChildren =
  {
    AuthenticatedPhotoStudioProjectsProjectIdRoute:
      AuthenticatedPhotoStudioProjectsProjectIdRoute,
  }

const AuthenticatedPhotoStudioRouteWithChildren =
  AuthenticatedPhotoStudioRoute._addFileChildren(
    AuthenticatedPhotoStudioRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAbTestsRoute: typeof AuthenticatedAbTestsRouteWithChildren
  AuthenticatedActionCenterRoute: typeof AuthenticatedActionCenterRoute
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataFixRoute: typeof AuthenticatedDataFixRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGroupingRoute: typeof AuthenticatedGroupingRoute
  AuthenticatedMartsRoute: typeof AuthenticatedMartsRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedPhotoStudioRoute: typeof AuthenticatedPhotoStudioRouteWithChildren
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedPurchasePlanRoute: typeof AuthenticatedPurchasePlanRoute
  AuthenticatedReputationRoute: typeof AuthenticatedReputationRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedStockControlRoute: typeof AuthenticatedStockControlRoute
  AuthenticatedCardsNmIdRoute: typeof AuthenticatedCardsNmIdRoute
  AuthenticatedCheckerNmIdRoute: typeof AuthenticatedCheckerNmIdRoute
  AuthenticatedCheckerFixedFileRoute: typeof AuthenticatedCheckerFixedFileRoute
  AuthenticatedProductsNmIdRoute: typeof AuthenticatedProductsNmIdRoute
  AuthenticatedSkuIdRoute: typeof AuthenticatedSkuIdRoute
  AuthenticatedCardsIndexRoute: typeof AuthenticatedCardsIndexRoute
  AuthenticatedCheckerIndexRoute: typeof AuthenticatedCheckerIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSkuIndexRoute: typeof AuthenticatedSkuIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbTestsRoute: AuthenticatedAbTestsRouteWithChildren,
  AuthenticatedActionCenterRoute: AuthenticatedActionCenterRoute,
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataFixRoute: AuthenticatedDataFixRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGroupingRoute: AuthenticatedGroupingRoute,
  AuthenticatedMartsRoute: AuthenticatedMartsRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedPhotoStudioRoute: AuthenticatedPhotoStudioRouteWithChildren,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedPurchasePlanRoute: AuthenticatedPurchasePlanRoute,
  AuthenticatedReputationRoute: AuthenticatedReputationRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedStockControlRoute: AuthenticatedStockControlRoute,
  AuthenticatedCardsNmIdRoute: AuthenticatedCardsNmIdRoute,
  AuthenticatedCheckerNmIdRoute: AuthenticatedCheckerNmIdRoute,
  AuthenticatedCheckerFixedFileRoute: AuthenticatedCheckerFixedFileRoute,
  AuthenticatedProductsNmIdRoute: AuthenticatedProductsNmIdRoute,
  AuthenticatedSkuIdRoute: AuthenticatedSkuIdRoute,
  AuthenticatedCardsIndexRoute: AuthenticatedCardsIndexRoute,
  AuthenticatedCheckerIndexRoute: AuthenticatedCheckerIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSkuIndexRoute: AuthenticatedSkuIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
