from __future__ import annotations

from copy import deepcopy


ENUM_LABELS: dict[str, dict[str, str]] = {
    "trust_state": {
        "trusted": "Доверенные",
        "data_blocked": "Данные заблокированы",
        "warning": "Требует внимания",
        "test_only": "Только для теста",
        "operational_provisional": "Операционно можно управлять",
        "financial_final": "Финально подтверждено",
        "blocked": "Заблокировано",
        "unknown": "Неопределено",
    },
    "sku_status": {
        "OK": "Норма",
        "DATA_BLOCKED": "Данные заблокированы",
        "NEEDS_REVIEW": "Нужна проверка",
        "ARCHIVED": "Архив",
        "SCALE": "Расти",
        "PROTECT_STOCK": "Защитить остаток",
        "REORDER": "Дозаказать",
        "LIQUIDATE": "Снижать остаток",
        "LIQUIDATE_FIRST": "Сначала распродать",
        "WAIT_DATA": "Ждём данные",
        "WATCH": "Наблюдать",
        "DO_NOT_BUY": "Не закупать",
        "STOP_PURCHASE": "Остановить закупку",
        "PRICE_REVIEW": "Проверить цену",
        "AD_REVIEW": "Проверить рекламу",
        "NEW_SKU": "Новый SKU",
    },
    "action_type": {
        "REORDER": "Дозаказ",
        "DATA_FIX_REQUIRED": "Исправить данные",
        "RECONCILIATION_REVIEW": "Проверить сверку",
        "FIX_COST_TRUST": "Подтвердить себестоимость",
        "MAP_UNMATCHED_SKU": "Связать SKU",
        "FIX_STOCK_SYNC": "Досинхронизировать остатки",
        "RECONCILE_FINANCE": "Сверить финансы",
        "FIX_AD_ALLOCATION": "Привязать рекламу к SKU",
        "FIX_PRICE_MAPPING": "Исправить маппинг цены",
        "DO_NOT_REORDER": "Не дозаказывать",
        "LIQUIDATE_STOCK": "Снижать остаток",
        "PRICE_INCREASE_REVIEW": "Проверить повышение цены",
        "AD_PAUSE_REVIEW": "Проверить остановку рекламы",
        "CARD_CONTENT_REVIEW": "Проверить контент карточки",
        "AD_REVIEW": "Проверить рекламу",
    },
    "priority": {
        "critical": "Критично",
        "high": "Высокий",
        "medium": "Средний",
        "low": "Низкий",
    },
    "cost_truth_level": {
        "supplier_confirmed": "Подтверждено поставщиком",
        "operator_baseline": "Операторская база",
        "placeholder": "Шаблонная себестоимость",
        "missing": "Нет себестоимости",
        "mixed": "Смешанный источник",
    },
    "alert_type": {
        "REORDER": "Дозаказ",
        "DATA_FIX_REQUIRED": "Исправить данные",
        "RECONCILIATION_REVIEW": "Проверить сверку",
        "FIX_COST_TRUST": "Подтвердить себестоимость",
        "MAP_UNMATCHED_SKU": "Связать SKU",
        "FIX_STOCK_SYNC": "Досинхронизировать остатки",
        "RECONCILE_FINANCE": "Сверить финансы",
        "FIX_AD_ALLOCATION": "Привязать рекламу к SKU",
        "FIX_PRICE_MAPPING": "Исправить маппинг цены",
        "DO_NOT_REORDER": "Не дозаказывать",
        "LIQUIDATE_STOCK": "Снижать остаток",
        "PRICE_INCREASE_REVIEW": "Проверить повышение цены",
        "AD_PAUSE_REVIEW": "Проверить рекламу",
    },
    "severity": {
        "info": "Инфо",
        "warning": "Предупреждение",
        "error": "Ошибка",
        "critical": "Критично",
    },
    "classification_status": {
        "detected": "Обнаружено",
        "classified": "Классифицировано",
        "mapped": "Связано со SKU",
        "ignored": "Игнорировано",
        "ignored_with_reason": "Игнорировано с причиной",
        "archived": "Архив",
    },
    "risk": {
        "reorder": "Нужен дозаказ",
        "out_of_stock": "Риск out-of-stock",
        "overstock": "Пересток",
        "below_break_even": "Цена ниже безубыточности",
        "below_target_margin": "Маржа ниже цели",
    },
    "status": {
        "new": "Новый",
        "in_progress": "В работе",
        "snoozed": "Отложен",
        "done": "Выполнен",
        "dismissed": "Скрыт",
        "resolved": "Решено",
        "open": "Открыт",
        "reopened": "Переоткрыт",
        "idle": "Ожидание",
        "running": "Выполняется",
        "completed": "Завершено",
        "failed": "Ошибка",
        "partial": "Частично",
        "skipped": "Пропущено",
        "queued": "В очереди",
    },
    "cost_source": {
        "manual_upload": "Ручная загрузка",
        "operator_trusted_manual": "Операторская базовая себестоимость",
        "placeholder_auto_template": "Автошаблон",
        "mixed": "Смешанный источник",
    },
    "expense_category": {
        "wb_commission": "Комиссия WB",
        "payment_processing": "Платежный эквайринг",
        "pvz_reward": "Вознаграждение ПВЗ",
        "wb_logistics": "Логистика WB",
        "wb_logistics_rebill": "Перевыставленная логистика WB",
        "storage": "Хранение",
        "acceptance": "Приемка",
        "penalty": "Штрафы",
        "deduction": "Удержания",
        "marketing_deduction": "Продвижение WB",
        "loyalty": "Лояльность и кешбэк",
        "additional_payment": "Доплаты",
        "seller_cogs": "Себестоимость продавца",
        "seller_other_expense": "Прочие расходы продавца",
        "ads_operational": "Операционная реклама",
        "unclassified": "Неклассифицированные расходы",
    },
    "manual_cost_labels": {
        "cost_price_label": "Себестоимость",
        "seller_other_expense_label": "Прочие расходы продавца",
        "total_unit_cost_label": "Себестоимость + прочие расходы",
    },
}


def get_enum_labels() -> dict[str, dict[str, str]]:
    return deepcopy(ENUM_LABELS)


def get_enum_mapping(name: str) -> dict[str, str]:
    return deepcopy(ENUM_LABELS.get(name, {}))
