from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

from app.models.accounts import WBAPICategory


ConnectorStatus = Literal["active", "not_implemented", "legacy_not_used"]


@dataclass(frozen=True, slots=True)
class WBConnectorInventoryEntry:
    connector_id: str
    domain: str
    endpoint_url: str
    token_category: str
    method: str
    request_shape: str
    pagination_cursor: str
    date_range_limit: str
    rate_limit: str
    success_shape: str
    no_data_shape: str
    status: ConnectorStatus
    db_target_tables: tuple[str, ...]
    dq_checks: tuple[str, ...]
    raw_response_storage: str
    client_path: str | None = None
    client_method: str | None = None
    source_doc: str | None = None
    compliance_notes: str = ""

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


WB_CONNECTOR_INVENTORY: tuple[WBConnectorInventoryEntry, ...] = (
    WBConnectorInventoryEntry(
        connector_id="product_cards.list_cards",
        domain="product_cards",
        endpoint_url="https://content-api.wildberries.ru/content/v2/get/cards/list",
        token_category=WBAPICategory.CONTENT.value,
        method="POST",
        request_shape="settings.sort, settings.cursor.limit, settings.cursor.updatedAt/nmID, settings.filter.withPhoto",
        pagination_cursor="Response cursor.total/cursor.updatedAt/cursor.nmID; repeat until total < limit.",
        date_range_limit="No date window; cursor is by listing update order.",
        rate_limit="Content category: 100 requests/min, 600 ms interval, burst 5.",
        success_shape="{cards: [...], cursor: {...}}",
        no_data_shape="{cards: [], cursor.total: 0} or cards omitted",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_product_cards",
            "wb_product_card_sizes",
            "wb_product_card_characteristics",
            "core_sku",
        ),
        dq_checks=(
            "unmatched_sku",
            "missing_chrt_id",
            "manual_cost_unresolved_sku",
            "manual_cost_ambiguous_match",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.product_cards.client.ProductCardsClient",
        client_method="list_cards",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
        compliance_notes="Uses current content host and cursor body contract.",
    ),
    WBConnectorInventoryEntry(
        connector_id="product_cards.list_tags",
        domain="product_cards",
        endpoint_url="https://content-api.wildberries.ru/content/v2/tags",
        token_category=WBAPICategory.CONTENT.value,
        method="GET",
        request_shape="No params.",
        pagination_cursor="None.",
        date_range_limit="None.",
        rate_limit="Content category: 100 requests/min, 600 ms interval, burst 5.",
        success_shape="{data: [...]} or {tags: [...]}",
        no_data_shape="Empty list.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_product_card_tags"),
        dq_checks=(),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.product_cards.client.ProductCardsClient",
        client_method="list_tags",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
    ),
    WBConnectorInventoryEntry(
        connector_id="product_cards.update_card",
        domain="product_cards",
        endpoint_url="https://content-api.wildberries.ru/content/v2/cards/update",
        token_category=WBAPICategory.CONTENT.value,
        method="POST",
        request_shape="Array of card snapshots with nmID, vendorCode, kizMarked, brand/title/description, dimensions, characteristics, sizes. The endpoint overwrites the listing, so unchanged supported fields must be preserved.",
        pagination_cursor="None.",
        date_range_limit="None.",
        rate_limit="Content update endpoint: 10 requests/min, 6 s interval, burst 5.",
        success_shape="{data: null, error: false, errorText: '', additionalErrors: {}}",
        no_data_shape="Not applicable.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_product_cards",
            "card_quality_issues",
            "card_quality_issue_status_history",
        ),
        dq_checks=(
            "card_quality_issue_wb_apply_rejected",
            "card_quality_update_draft_errors",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.services.card_quality.CardQualityAnalysisService",
        client_method="_submit_wb_card_update",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
        compliance_notes="Only explicit user-confirmed Checker fixes call this write path; photos, video, tags and prices are excluded per WB docs.",
    ),
    WBConnectorInventoryEntry(
        connector_id="prices.list_goods",
        domain="prices",
        endpoint_url="https://discounts-prices-api.wildberries.ru/api/v2/list/goods/filter",
        token_category=WBAPICategory.PRICES.value,
        method="GET",
        request_shape="limit, offset; optional filterNmID is not used for full sync.",
        pagination_cursor="Offset pagination; continue while listGoods count == limit.",
        date_range_limit="No date window.",
        rate_limit="Prices and Discounts category; governed by WB method limits and 429 headers.",
        success_shape="{data: {listGoods: [...]}}",
        no_data_shape="{data: {listGoods: []}}",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_prices",
            "wb_price_snapshots",
            "core_sku",
        ),
        dq_checks=("price_zero_or_too_low", "price_jump", "unmatched_sku"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.prices.client.PricesClient",
        client_method="list_goods",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
    ),
    WBConnectorInventoryEntry(
        connector_id="prices.list_sizes",
        domain="prices",
        endpoint_url="https://discounts-prices-api.wildberries.ru/api/v2/list/goods/size/nm",
        token_category=WBAPICategory.PRICES.value,
        method="GET",
        request_shape="nmID, limit=1000, offset=0.",
        pagination_cursor="Offset pagination available; current sync fetches one page per nmID.",
        date_range_limit="No date window.",
        rate_limit="Prices and Discounts category; governed by WB method limits and 429 headers.",
        success_shape="{data: {listGoods: [...]}}",
        no_data_shape="{data: {listGoods: []}}",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_price_sizes"),
        dq_checks=("missing_chrt_id", "price_zero_or_too_low"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.prices.client.PricesClient",
        client_method="list_sizes",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
    ),
    WBConnectorInventoryEntry(
        connector_id="prices.upload_state",
        domain="prices",
        endpoint_url="https://discounts-prices-api.wildberries.ru/api/v2/history/tasks, /api/v2/history/goods/task, /api/v2/buffer/tasks, /api/v2/buffer/goods/task",
        token_category=WBAPICategory.PRICES.value,
        method="GET",
        request_shape="uploadID; detail endpoints also use limit and offset.",
        pagination_cursor="Offset pagination for goods task details.",
        date_range_limit="Upload task history scope controlled by WB.",
        rate_limit="Prices and Discounts category; governed by WB method limits and 429 headers.",
        success_shape="{data: {historyGoods|bufferGoods: [...]}}",
        no_data_shape="Missing data object or empty goods list.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_price_upload_tasks",
            "wb_price_upload_task_rows",
        ),
        dq_checks=(
            "prices_processed_history_unavailable",
            "prices_buffer_history_unavailable",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.prices.client.PricesClient",
        client_method="processed_tasks",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
    ),
    WBConnectorInventoryEntry(
        connector_id="prices.quarantine_goods",
        domain="prices",
        endpoint_url="https://discounts-prices-api.wildberries.ru/api/v2/quarantine/goods",
        token_category=WBAPICategory.PRICES.value,
        method="GET",
        request_shape="limit, offset.",
        pagination_cursor="Offset pagination; continue while rows count == limit.",
        date_range_limit="Current WB quarantine state.",
        rate_limit="Prices and Discounts category; governed by WB method limits and 429 headers.",
        success_shape="{data: {quarantineGoods: [...]}} or {goods: [...]}",
        no_data_shape="Empty quarantineGoods/goods list.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_price_quarantine"),
        dq_checks=("price_zero_or_too_low", "price_jump"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.prices.client.PricesClient",
        client_method="quarantine_goods",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/work-with-products",
    ),
    WBConnectorInventoryEntry(
        connector_id="promotions.calendar",
        domain="promotions",
        endpoint_url="https://dp-calendar-api.wildberries.ru/api/v1/calendar/promotions, /api/v1/calendar/promotions/details, /api/v1/calendar/promotions/nomenclatures",
        token_category=WBAPICategory.PROMOTION.value,
        method="GET",
        request_shape="startDateTime, endDateTime, allPromo, limit/offset; details promotionIDs; nomenclatures promotionID + inAction.",
        pagination_cursor="Offset pagination for promotions and nomenclatures.",
        date_range_limit="Default sync window: previous 30 days through next 90 days; backfill supports explicit date ranges.",
        rate_limit="Promotions Calendar category; 10 requests per 6 seconds for Personal/Service tokens, Base 1 request/hour per WB docs.",
        success_shape="{data: {promotions: [...]}} and {data: {nomenclatures: [...]}}",
        no_data_shape="Empty promotions/nomenclatures list.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_promotion_calendar",
            "wb_promotion_nomenclatures",
        ),
        dq_checks=("promotions_nomenclatures_unavailable",),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.promotions.client.PromotionsClient",
        client_method="promotions/details/nomenclatures",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/promotion",
        compliance_notes="Read-only sync. Promotion upload/write is intentionally not automated without explicit user confirmation.",
    ),
    WBConnectorInventoryEntry(
        connector_id="orders.fetch_orders",
        domain="orders",
        endpoint_url="https://statistics-api.wildberries.ru/api/v1/supplier/orders",
        token_category=WBAPICategory.STATISTICS.value,
        method="GET",
        request_shape="dateFrom.",
        pagination_cursor="No cursor; dateFrom incremental sync.",
        date_range_limit="WB guarantees storage for no more than 90 days; data is preliminary.",
        rate_limit="Statistics Main Reports category; governed by WB method limits and 429 headers.",
        success_shape="Array of order rows.",
        no_data_shape="Empty array.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_orders"),
        dq_checks=(
            "order_without_sale_or_return",
            "finance_reconciliation_mismatch",
            "unmatched_sku",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.orders.client.OrdersClient",
        client_method="fetch_orders",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/reports",
    ),
    WBConnectorInventoryEntry(
        connector_id="sales.fetch_sales",
        domain="sales",
        endpoint_url="https://statistics-api.wildberries.ru/api/v1/supplier/sales",
        token_category=WBAPICategory.STATISTICS.value,
        method="GET",
        request_shape="dateFrom.",
        pagination_cursor="No cursor; dateFrom incremental sync.",
        date_range_limit="WB guarantees storage for no more than 90 days; data is preliminary.",
        rate_limit="Statistics Main Reports category; governed by WB method limits and 429 headers.",
        success_shape="Array of sale/return rows.",
        no_data_shape="Empty array.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_sales"),
        dq_checks=(
            "sale_without_finance",
            "sales_without_stock",
            "finance_reconciliation_mismatch",
            "unmatched_sku",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.sales.client.SalesClient",
        client_method="fetch_sales",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/reports",
    ),
    WBConnectorInventoryEntry(
        connector_id="stocks.warehouse_remains",
        domain="stocks",
        endpoint_url="https://seller-analytics-api.wildberries.ru/api/v1/warehouse_remains",
        token_category=WBAPICategory.ANALYTICS.value,
        method="GET",
        request_shape="groupByNm=true, groupByBarcode=true, groupBySize=true; then task status and download by task_id.",
        pagination_cursor="Async task id; poll status, then download report.",
        date_range_limit="Current inventory snapshot.",
        rate_limit="Analytics stocks report; local pre-request spacing 10 s plus 429 headers.",
        success_shape="Create task returns task id; download returns rows/list data.",
        no_data_shape="Task without rows or empty report.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_stock_snapshots",
            "wb_stock_snapshot_rows",
            "mart_stock_daily",
        ),
        dq_checks=("stock_without_sales", "sales_without_stock", "unmatched_sku"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.stocks.client.StocksClient",
        client_method="create_warehouse_remains_task",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/analytics",
    ),
    WBConnectorInventoryEntry(
        connector_id="finance.sales_reports_list",
        domain="finance",
        endpoint_url="https://finance-api.wildberries.ru/api/finance/v1/sales-reports/list",
        token_category=WBAPICategory.FINANCE.value,
        method="POST",
        request_shape="dateFrom, dateTo.",
        pagination_cursor="No cursor.",
        date_range_limit="Finance period window; sync defaults to 30 days or explicit backfill.",
        rate_limit="Finance category; local pre-request spacing 61 s plus 429 headers.",
        success_shape="{reports: [...]} or {data: [...]}",
        no_data_shape="Empty reports/data list.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_realization_reports"),
        dq_checks=(
            "finance_reconciliation_mismatch",
            "finance_without_sale",
            "sale_without_finance",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.finance.client.FinanceClient",
        client_method="sales_reports_list",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/financial-reports-and-accounting",
    ),
    WBConnectorInventoryEntry(
        connector_id="finance.sales_reports_detailed",
        domain="finance",
        endpoint_url="https://finance-api.wildberries.ru/api/finance/v1/sales-reports/detailed",
        token_category=WBAPICategory.FINANCE.value,
        method="POST",
        request_shape="dateFrom, dateTo, period=weekly, rrdId, limit, optional fields.",
        pagination_cursor="rrdId cursor; repeat with last row rrdId until fewer than limit or 204/noData.",
        date_range_limit="Finance period window; sync defaults to 30 days or explicit backfill.",
        rate_limit="Finance category; local pre-request spacing 61 s plus 429 headers.",
        success_shape="{report|reports|data: [...]}",
        no_data_shape="HTTP 204 stored as {noData: true}; empty report/data also ends page loop.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_realization_report_rows",
            "mart_finance_reconciliation",
            "mart_expense_daily",
            "mart_sku_daily",
        ),
        dq_checks=(
            "finance_reconciliation_mismatch",
            "finance_without_sale",
            "sale_without_finance",
            "expense_unclassified",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.finance.client.FinanceClient",
        client_method="sales_reports_detailed",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/financial-reports-and-accounting",
        compliance_notes="Current replacement for deprecated /api/v5/supplier/reportDetailByPeriod.",
    ),
    WBConnectorInventoryEntry(
        connector_id="finance.legacy_report_detail_by_period",
        domain="finance",
        endpoint_url="https://statistics-api.wildberries.ru/api/v5/supplier/reportDetailByPeriod",
        token_category=WBAPICategory.STATISTICS.value,
        method="GET",
        request_shape="dateFrom, dateTo, limit, rrdid, period.",
        pagination_cursor="rrdid cursor until 204.",
        date_range_limit="Legacy realization report period.",
        rate_limit="Deprecated legacy method.",
        success_shape="Array of legacy rows.",
        no_data_shape="HTTP 204.",
        status="legacy_not_used",
        db_target_tables=(),
        dq_checks=(),
        raw_response_storage="Not used by production sync.",
        client_path=None,
        client_method=None,
        source_doc="https://dev.wildberries.ru/en/docs/openapi/financial-reports-and-accounting",
        compliance_notes="Official docs mark this deprecated and scheduled for removal; production code must not call it.",
    ),
    WBConnectorInventoryEntry(
        connector_id="finance.acquiring",
        domain="finance",
        endpoint_url="https://finance-api.wildberries.ru/api/finance/v1/acquiring/list, /api/finance/v1/acquiring/detailed",
        token_category=WBAPICategory.FINANCE.value,
        method="POST",
        request_shape="dateFrom, dateTo; detailed also rrdId, limit, optional fields.",
        pagination_cursor="rrdId cursor for detailed rows.",
        date_range_limit="Finance period window; only available to Russian sellers per WB docs.",
        rate_limit="Finance category; local pre-request spacing 61 s plus 429 headers.",
        success_shape="{reports|data: [...]} for list and {report|data: [...]} for detailed.",
        no_data_shape="Empty lists or 204 stored as {noData: true}.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_acquiring_reports",
            "wb_acquiring_report_rows",
        ),
        dq_checks=("acquiring_sync_unsupported", "acquiring_sync_failed"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.finance.client.FinanceClient",
        client_method="acquiring_reports_list",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/financial-reports-and-accounting",
    ),
    WBConnectorInventoryEntry(
        connector_id="analytics.funnel_history",
        domain="analytics",
        endpoint_url="https://seller-analytics-api.wildberries.ru/api/analytics/v3/sales-funnel/products/history",
        token_category=WBAPICategory.ANALYTICS.value,
        method="POST",
        request_shape="selectedPeriod.start/end, nmIds, skipDeletedNm, aggregationLevel=day.",
        pagination_cursor="No page cursor in current usage; sync batches nmIds.",
        date_range_limit="Maximum last week for product-card per-days history.",
        rate_limit="Analytics sales funnel: 3 requests/min, 20 s interval, burst 3.",
        success_shape="Array of product history rows.",
        no_data_shape="Empty array.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_card_funnel_daily"),
        dq_checks=("checker_opportunity_estimates",),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.analytics.client.AnalyticsClient",
        client_method="funnel_history",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/analytics",
    ),
    WBConnectorInventoryEntry(
        connector_id="analytics.region_sales",
        domain="analytics",
        endpoint_url="https://seller-analytics-api.wildberries.ru/api/v1/analytics/region-sale",
        token_category=WBAPICategory.ANALYTICS.value,
        method="GET",
        request_shape="dateFrom, dateTo.",
        pagination_cursor="None.",
        date_range_limit="Analytics window from sync/backfill.",
        rate_limit="Analytics category; governed by WB method limits and 429 headers.",
        success_shape="{report: [...]}",
        no_data_shape="Empty report list.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_region_sales_daily"),
        dq_checks=(),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.analytics.client.AnalyticsClient",
        client_method="region_sales",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/analytics",
    ),
    WBConnectorInventoryEntry(
        connector_id="analytics.hidden_products",
        domain="analytics",
        endpoint_url="https://seller-analytics-api.wildberries.ru/api/v1/analytics/banned-products/blocked, /api/v1/analytics/banned-products/shadowed",
        token_category=WBAPICategory.ANALYTICS.value,
        method="GET",
        request_shape="sort=nmId, order=asc.",
        pagination_cursor="None.",
        date_range_limit="Current hidden/blocked state.",
        rate_limit="Analytics category; governed by WB method limits and 429 headers.",
        success_shape="{report: [...]}",
        no_data_shape="Empty report list.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_hidden_products"),
        dq_checks=("checker_visibility_warning",),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.analytics.client.AnalyticsClient",
        client_method="blocked_products",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/analytics",
    ),
    WBConnectorInventoryEntry(
        connector_id="ads.campaigns",
        domain="ads",
        endpoint_url="https://advert-api.wildberries.ru/api/advert/v2/adverts",
        token_category=WBAPICategory.PROMOTION.value,
        method="GET",
        request_shape="No params.",
        pagination_cursor="None.",
        date_range_limit="Current campaigns.",
        rate_limit="Promotion category; governed by WB method limits and 429 headers.",
        success_shape="{adverts: [...]} or {data: [...]}",
        no_data_shape="Empty adverts/data list.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_ad_campaigns",
            "wb_ad_campaign_items",
        ),
        dq_checks=("ad_spend_without_sku", "ads_overallocated_to_profitability"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.ads.client.AdsClient",
        client_method="campaigns",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/promotion",
    ),
    WBConnectorInventoryEntry(
        connector_id="ads.full_stats",
        domain="ads",
        endpoint_url="https://advert-api.wildberries.ru/adv/v3/fullstats",
        token_category=WBAPICategory.PROMOTION.value,
        method="GET",
        request_shape="ids comma list, beginDate, endDate.",
        pagination_cursor="Batched by campaign ids; no response cursor.",
        date_range_limit="Sync defaults to 7-day window unless backfilled.",
        rate_limit="Full stats local pre-request spacing 20 s plus 429 headers.",
        success_shape="Array of campaign stat objects or {data: [...]}",
        no_data_shape="Empty array/data.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_ad_stats_daily"),
        dq_checks=(
            "ad_spend_without_sku",
            "ads_overallocated_to_profitability",
            "ad_spend_without_sales",
        ),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.ads.client.AdsClient",
        client_method="full_stats",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/promotion",
    ),
    WBConnectorInventoryEntry(
        connector_id="ads.cluster_stats",
        domain="ads",
        endpoint_url="https://advert-api.wildberries.ru/adv/v1/normquery/stats",
        token_category=WBAPICategory.PROMOTION.value,
        method="POST",
        request_shape="from, to, items[{advertId,nmId}].",
        pagination_cursor="Batched local item list; no response cursor.",
        date_range_limit="Sync window defaults to 7 days unless backfilled.",
        rate_limit="WB limit 10 requests/min; sync sends one batch of up to 100 advert/nm items per run.",
        success_shape="{items: [{advertId, nmId, dailyStats: [{date, stat: {...}}]}]}",
        no_data_shape="Empty stats/data/items.",
        status="active",
        db_target_tables=("raw_wb_api_responses", "wb_ad_cluster_stats"),
        dq_checks=("ad_spend_without_sku",),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.ads.client.AdsClient",
        client_method="cluster_stats",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/promotion",
    ),
    WBConnectorInventoryEntry(
        connector_id="tariffs.common",
        domain="tariffs",
        endpoint_url="https://common-api.wildberries.ru/api/v1/tariffs/commission, /api/v1/tariffs/box, /api/v1/tariffs/pallet, /api/v1/tariffs/return, /api/tariffs/v1/acceptance/coefficients",
        token_category=WBAPICategory.TARIFFS.value,
        method="GET",
        request_shape="locale for commission; date for box/pallet/return; optional warehouseIDs for acceptance.",
        pagination_cursor="None.",
        date_range_limit="Current or requested tariff date; acceptance returns next 14 days.",
        rate_limit="Tariffs/common API limits vary by method; 429 headers honored.",
        success_shape="{report: [...]}, {response.data.warehouseList: [...]}, or array.",
        no_data_shape="Empty report/warehouseList/array.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_tariff_commissions",
            "wb_tariff_boxes",
            "wb_tariff_pallets",
            "wb_tariff_returns",
            "wb_tariff_acceptance",
        ),
        dq_checks=(),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.tariffs.client.TariffsClient",
        client_method="commissions",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/wb-tariffs",
        compliance_notes="WB allows any token category for tariffs; app keeps a dedicated tariffs token for least confusion.",
    ),
    WBConnectorInventoryEntry(
        connector_id="documents.documents",
        domain="documents",
        endpoint_url="https://documents-api.wildberries.ru/api/v1/documents/categories, /api/v1/documents/list",
        token_category=WBAPICategory.DOCUMENTS.value,
        method="GET",
        request_shape="locale for categories; locale, beginTime, endTime, sort, order for list.",
        pagination_cursor="None.",
        date_range_limit="Sync defaults to 30 days unless backfilled.",
        rate_limit="Documents local pre-request spacing 10 s plus 429 headers.",
        success_shape="{data: {categories|documents: [...]}} or {documents: [...]}",
        no_data_shape="Empty categories/documents list.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_document_categories",
            "wb_documents",
        ),
        dq_checks=(),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.documents.client.DocumentsClient",
        client_method="documents",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/financial-reports-and-accounting",
    ),
    WBConnectorInventoryEntry(
        connector_id="supplies.fbw",
        domain="supplies",
        endpoint_url="https://supplies-api.wildberries.ru/api/v1/warehouses, /api/v1/acceptance/options, /api/v1/supplies, /api/v1/supplies/{ID}, /api/v1/supplies/{ID}/goods, /api/v1/supplies/{ID}/package",
        token_category=WBAPICategory.SUPPLIES.value,
        method="GET/POST",
        request_shape="Warehouses no params; supplies limit/offset; detail endpoints by supply ID; acceptance options body items.",
        pagination_cursor="Offset pagination for supplies and goods.",
        date_range_limit="Current supplies plus incremental enrichment of recent/changed supplies.",
        rate_limit="Supplies category; local 0.35 s enrichment pause plus 429 handling.",
        success_shape="List or {data/supplies/warehouses: [...]} depending endpoint.",
        no_data_shape="Empty list/data.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "wb_supply_warehouses",
            "wb_supply_acceptance_options",
            "wb_supplies",
            "wb_supply_goods",
            "wb_supply_packages",
        ),
        dq_checks=("supply_discrepancy_candidates", "unmatched_sku"),
        raw_response_storage="DomainSyncBase._request_json",
        client_path="app.modules.supplies.client.SuppliesClient",
        client_method="supplies",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/orders-fbw",
    ),
    WBConnectorInventoryEntry(
        connector_id="feedbacks_questions.reputation",
        domain="reputation",
        endpoint_url="https://feedbacks-api.wildberries.ru/api/v1/feedbacks, /api/v1/questions, /api/v1/feedbacks/answer, /api/v1/questions",
        token_category=WBAPICategory.FEEDBACKS_QUESTIONS.value,
        method="GET/POST/PATCH",
        request_shape="GET isAnswered,take,skip,order; answer body id,text.",
        pagination_cursor="take/skip pagination; sync caps pages per source and dedupes repeated pages.",
        date_range_limit="WB feedbacks/questions history exposed by endpoint; local sync reads answered and unanswered pages.",
        rate_limit="Feedbacks and Questions category: 3 requests/s, 333 ms interval, burst 6.",
        success_shape="{data: {feedbacks|questions: [...]}} or similar WB envelope.",
        no_data_shape="Empty rows from adapter.",
        status="active",
        db_target_tables=(
            "raw_wb_api_responses",
            "reputation_items",
            "operator_drafts",
            "result_events",
        ),
        dq_checks=("reputation_sync_failed",),
        raw_response_storage="ReputationService._store_wb_raw_response",
        client_path="app.services.reputation.ReputationService",
        client_method="_fetch_wb_items",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/user-communication",
        compliance_notes="Must never use content token; buyer chat remains read-only/not configured separately.",
    ),
    WBConnectorInventoryEntry(
        connector_id="buyer_chat",
        domain="buyer_chat",
        endpoint_url="https://buyer-chat-api.wildberries.ru",
        token_category=WBAPICategory.BUYER_CHAT.value,
        method="GET/POST",
        request_shape="Not implemented in production connector.",
        pagination_cursor="Not implemented.",
        date_range_limit="Not implemented.",
        rate_limit="Buyer Chat category; must be checked before implementation.",
        success_shape="Not implemented.",
        no_data_shape="Not implemented.",
        status="not_implemented",
        db_target_tables=(),
        dq_checks=(),
        raw_response_storage="No production connector.",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/user-communication",
        compliance_notes="Portal chat UI is local/read-only; no WB buyer-chat token is consumed.",
    ),
    WBConnectorInventoryEntry(
        connector_id="buyer_returns",
        domain="buyer_returns",
        endpoint_url="https://returns-api.wildberries.ru/api/v1/claims, /api/v1/claim",
        token_category=WBAPICategory.BUYER_RETURNS.value,
        method="GET/PATCH",
        request_shape="Not implemented in production connector.",
        pagination_cursor="Not implemented.",
        date_range_limit="Not implemented.",
        rate_limit="Buyer Returns category; must be checked before implementation.",
        success_shape="Not implemented.",
        no_data_shape="Not implemented.",
        status="not_implemented",
        db_target_tables=(),
        dq_checks=(),
        raw_response_storage="No production connector.",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/user-communication",
        compliance_notes="Current claims module uses local/internal evidence and does not call WB returns APIs.",
    ),
    WBConnectorInventoryEntry(
        connector_id="users.access",
        domain="users",
        endpoint_url="https://user-management-api.wildberries.ru",
        token_category=WBAPICategory.USERS.value,
        method="GET/POST/PUT",
        request_shape="Not implemented in production connector.",
        pagination_cursor="Not implemented.",
        date_range_limit="Not implemented.",
        rate_limit="Users category; must be checked before implementation.",
        success_shape="Not implemented.",
        no_data_shape="Not implemented.",
        status="not_implemented",
        db_target_tables=(),
        dq_checks=(),
        raw_response_storage="No production connector.",
        source_doc="https://dev.wildberries.ru/en/docs/openapi/api-information",
    ),
)


def inventory_by_connector_id() -> dict[str, WBConnectorInventoryEntry]:
    return {entry.connector_id: entry for entry in WB_CONNECTOR_INVENTORY}


def active_inventory() -> tuple[WBConnectorInventoryEntry, ...]:
    return tuple(entry for entry in WB_CONNECTOR_INVENTORY if entry.status == "active")


def inventory_as_markdown() -> str:
    headers = (
        "domain",
        "connector_id",
        "WB endpoint URL",
        "token category",
        "method",
        "pagination/cursor",
        "date range limit",
        "rate limit",
        "success/no-data",
        "status",
        "DB target tables",
        "DQ checks",
        "raw storage",
    )
    lines = [
        "# WB Connector Compliance Inventory",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for entry in WB_CONNECTOR_INVENTORY:
        lines.append(
            "| "
            + " | ".join(
                str(value).replace("|", "\\|").replace("\n", " ")
                for value in (
                    entry.domain,
                    entry.connector_id,
                    entry.endpoint_url,
                    entry.token_category,
                    entry.method,
                    entry.pagination_cursor,
                    entry.date_range_limit,
                    entry.rate_limit,
                    f"{entry.success_shape} / {entry.no_data_shape}",
                    entry.status,
                    ", ".join(entry.db_target_tables) or "-",
                    ", ".join(entry.dq_checks) or "-",
                    entry.raw_response_storage,
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Compliance Notes",
            "",
            "- Feedbacks/questions use the `feedbacks_questions` category, not `content`.",
            "- Buyer chat, buyer returns, and seller users are explicitly not implemented as WB connectors.",
            "- Finance sync uses `/api/finance/v1/sales-reports/*`; legacy `/api/v5/supplier/reportDetailByPeriod` is marked `legacy_not_used`.",
            "- Raw WB responses for active domain sync connectors are stored through `raw_wb_api_responses`.",
        ]
    )
    return "\n".join(lines) + "\n"
